#!/bin/bash

echo "🔍 Investigating Why Geolocation Stopped Working on Your Mac"
echo "=========================================================="

echo ""
echo "📊 System Information:"
echo "• macOS Version: $(sw_vers -productVersion)"
echo "• Build: $(sw_vers -buildVersion)"
echo "• Chrome Version: Check chrome://version/"
echo ""

echo "🌐 Network Information:"
echo "• Wi-Fi Connected: $(networksetup -getairportnetwork en0 2>/dev/null || echo 'Not available')"
echo "• Ethernet Connected: $(ifconfig en0 | grep 'inet ' | awk '{print $2}' || echo 'Not connected')"
echo ""

echo "🛠️ Checking Location Services Status:"
if [[ -x "$(command -v sqlite3)" ]]; then
    # Check if Location Services is enabled globally
    LOCATION_ENABLED=$(sqlite3 /var/db/LocationCache/clients.plist.db "SELECT service FROM clients WHERE service = 'com.apple.locationd.bundle-/System/Library/LocationBundles/CoreLocation.bundle';" 2>/dev/null || echo "")
    if [[ -n "$LOCATION_ENABLED" ]]; then
        echo "✅ Location Services appears to be enabled"
    else
        echo "❌ Location Services may be disabled"
    fi
else
    echo "ℹ️  Cannot check Location Services database (requires admin access)"
fi

echo ""
echo "🔍 Common Causes for macOS Location Breaking:"
echo ""
echo "1. 🔒 PRIVACY SETTINGS CHANGES"
echo "   • Recent macOS updates often reset location permissions"
echo "   • System Preferences > Security & Privacy > Location Services"
echo "   • Check if Chrome/Safari has location permission"
echo ""
echo "2. 📱 macOS UPDATES"
echo "   • macOS 14.6+ introduced stricter CoreLocation policies"
echo "   • macOS 15+ (Sequoia) has enhanced privacy controls"
echo "   • Each update can break existing location permissions"
echo ""
echo "3. 🌐 BROWSER SECURITY UPDATES"
echo "   • Chrome 120+ has stricter location policies"
echo "   • Safari updates with WebKit security enhancements"
echo "   • HTTPS requirements for location access"
echo ""
echo "4. 🔧 NETWORK CONFIGURATION"
echo "   • VPN settings changes"
echo "   • DNS resolver changes"
echo "   • Firewall rule updates"
echo ""
echo "5. 📍 LOCATION DATABASE CORRUPTION"
echo "   • macOS location cache can become corrupted"
echo "   • Requires clearing location service caches"
echo ""

echo "🎯 QUICK FIXES TO TRY:"
echo ""
echo "1. Reset Browser Location Permissions:"
echo "   • Chrome: chrome://settings/content/location"
echo "   • Clear all site permissions and re-allow"
echo ""
echo "2. Reset macOS Location Services:"
echo "   • System Preferences > Security & Privacy > Location Services"
echo "   • Turn off Location Services, wait 10 seconds, turn back on"
echo "   • Re-enable browser permissions"
echo ""
echo "3. Clear Location Caches:"
echo "   • We can reset the app's location failure memory"
echo ""
echo "4. Test with Different Browser:"
echo "   • Try Safari vs Chrome vs Firefox"
echo "   • This helps identify if it's browser-specific"
echo ""

echo "🧪 IMMEDIATE TESTS:"
echo "1. Open: http://localhost:3000"
echo "2. Try location detection"
echo "3. Check browser console for specific error codes"
echo "4. Note if IP fallback works (should show Madrid, Spain)"
echo ""

echo "📝 DEBUGGING STEPS:"
echo "1. Test location in vanilla browser:"
echo "   • Go to: https://www.google.com/maps"
echo "   • Click location button"
echo "   • See if it works there"
echo ""
echo "2. Check system location test:"
echo "   • Open Terminal"
echo "   • Run: sudo locationd -d"
echo "   • This shows system-level location issues"
echo ""

echo "✅ Ready to debug! Let's find out what changed."
