/**
 * Auto-generated by scripts/generate-species-image-map.ts
 * Generated at: 2025-09-27T21:57:12.000Z
 */

export interface SpeciesImageInfo {
  code: string;
  name: string;
  scientificName: string | null;
  slug: string;
  image: string;
  mobile?: string | null;
  thumb?: string | null;
}

export const SPECIES_IMAGE_MAP: Record<string, SpeciesImageInfo> = {
  'AMB': { code: 'AMB', name: 'Greater Amberjack', scientificName: 'Seriola dumerili', slug: 'greater-amberjack', image: '/webp/greater-amberjack.webp', mobile: '/webp/greater-amberjack-mobile.webp', thumb: '/webp/greater-amberjack-thumb.webp' },
  'BBR': { code: 'BBR', name: 'Black Seabream', scientificName: 'Spondyliosoma cantharus', slug: 'black-bream', image: '/webp/black-bream.webp', mobile: '/webp/black-bream-mobile.webp', thumb: '/webp/black-bream-thumb.webp' },
  'BRI': { code: 'BRI', name: 'Brill', scientificName: 'Scophthalmus rhombus', slug: 'brill', image: '/webp/brill.webp', mobile: '/webp/brill-mobile.webp', thumb: '/webp/brill-thumb.webp' },
  'BSB': { code: 'BSB', name: 'Red Seabream', scientificName: 'Pagrus pagrus', slug: 'red-bream', image: '/webp/red-bream.webp', mobile: '/webp/red-bream-mobile.webp', thumb: '/webp/red-bream-thumb.webp' },
  'COD': { code: 'COD', name: 'Atlantic Cod', scientificName: 'Gadus morhua', slug: 'cod', image: '/webp/cod.webp', mobile: '/webp/cod-mobile.webp', thumb: '/webp/cod-thumb.webp' },
  'CON': { code: 'CON', name: 'Conger Eel', scientificName: 'Conger conger', slug: 'conger', image: '/webp/conger.webp', mobile: '/webp/conger-mobile.webp', thumb: '/webp/conger-thumb.webp' },
  'CUC': { code: 'CUC', name: 'Cuckoo Wrasse', scientificName: 'Labrus mixtus', slug: 'cuckoo-wrasse', image: '/webp/cuckoo-wrasse.webp', mobile: '/webp/cuckoo-wrasse-mobile.webp', thumb: '/webp/cuckoo-wrasse-thumb.webp' },
  'CUT': { code: 'CUT', name: 'Common Cuttlefish', scientificName: 'Sepia officinalis', slug: 'cuttlefish', image: '/webp/cuttlefish.webp', mobile: '/webp/cuttlefish-mobile.webp', thumb: '/webp/cuttlefish-thumb.webp' },
  'DAB': { code: 'DAB', name: 'Dab', scientificName: 'Limanda limanda', slug: 'dab', image: '/webp/dab.webp', mobile: '/webp/dab-mobile.webp', thumb: '/webp/dab-thumb.webp' },
  'DEN': { code: 'DEN', name: 'Common Dentex', scientificName: 'Dentex dentex', slug: 'dentex', image: '/webp/dentex.webp', mobile: '/webp/dentex-mobile.webp', thumb: '/webp/dentex-thumb.webp' },
  'DOG': { code: 'DOG', name: 'Small-spotted Catshark', scientificName: 'Scyliorhinus canicula', slug: 'small-spotted-catshark', image: '/webp/small-spotted-catshark.webp', mobile: '/webp/small-spotted-catshark-mobile.webp', thumb: '/webp/small-spotted-catshark-thumb.webp' },
  'FLO': { code: 'FLO', name: 'Flounder', scientificName: 'Platichthys flesus', slug: 'flounder', image: '/webp/flounder.webp', mobile: '/webp/flounder-mobile.webp', thumb: '/webp/flounder-thumb.webp' },
  'GAR': { code: 'GAR', name: 'Garfish', scientificName: 'Belone belone', slug: 'garfish', image: '/webp/garfish.webp', mobile: '/webp/garfish-mobile.webp', thumb: '/webp/garfish-thumb.webp' },
  'GMU': { code: 'GMU', name: 'Grey Mullet', scientificName: 'Chelon labrosus', slug: 'grey-mullet', image: '/webp/grey-mullet.webp', mobile: '/webp/grey-mullet-mobile.webp', thumb: '/webp/grey-mullet-thumb.webp' },
  'GUR': { code: 'GUR', name: 'Tub Gurnard', scientificName: 'Chelidonichthys lucerna', slug: 'tub-gurnard', image: '/webp/tub-gurnard.webp', mobile: '/webp/tub-gurnard-mobile.webp', thumb: '/webp/tub-gurnard-thumb.webp' },
  'HAD': { code: 'HAD', name: 'Haddock', scientificName: 'Melanogrammus aeglefinus', slug: 'haddock', image: '/webp/haddock.webp', mobile: '/webp/haddock-mobile.webp', thumb: '/webp/haddock-thumb.webp' },
  'HER': { code: 'HER', name: 'Atlantic Herring', scientificName: 'Clupea harengus', slug: 'herring', image: '/webp/herring.webp', mobile: '/webp/herring-mobile.webp', thumb: '/webp/herring-thumb.webp' },
  'HOM': { code: 'HOM', name: 'Horse Mackerel', scientificName: 'Trachurus trachurus', slug: 'horse-mackerel', image: '/webp/horse-mackerel.webp', mobile: '/webp/horse-mackerel-mobile.webp', thumb: '/webp/horse-mackerel-thumb.webp' },
  'JDO': { code: 'JDO', name: 'John Dory', scientificName: 'Zeus faber', slug: 'john-dory', image: '/webp/john-dory.webp', mobile: '/webp/john-dory-mobile.webp', thumb: '/webp/john-dory-thumb.webp' },
  'LIN': { code: 'LIN', name: 'Common Ling', scientificName: 'Molva molva', slug: 'ling', image: '/webp/ling.webp', mobile: '/webp/ling-mobile.webp', thumb: '/webp/ling-thumb.webp' },
  'LIT': { code: 'LIT', name: 'Little Tunny', scientificName: 'Euthynnus alletteratus', slug: 'little-tunny', image: '/webp/little-tunny.webp', mobile: '/webp/little-tunny-mobile.webp', thumb: '/webp/little-tunny-thumb.webp' },
  'MAC': { code: 'MAC', name: 'Atlantic Mackerel', scientificName: 'Scomber scombrus', slug: 'atlantic-mackerel', image: '/webp/atlantic-mackerel.webp', mobile: '/webp/atlantic-mackerel-mobile.webp', thumb: '/webp/atlantic-mackerel-thumb.webp' },
  'MEG': { code: 'MEG', name: 'Megrim', scientificName: 'Lepidorhombus whiffiagonis', slug: 'megrim', image: '/webp/megrim.webp', mobile: '/webp/megrim-mobile.webp', thumb: '/webp/megrim-thumb.webp' },
  'MUL': { code: 'MUL', name: 'Flathead Grey Mullet', scientificName: 'Mugil cephalus', slug: 'flathead-grey-mullet', image: '/webp/flathead-grey-mullet.webp', mobile: '/webp/flathead-grey-mullet-mobile.webp', thumb: '/webp/flathead-grey-mullet-thumb.webp' },
  'OCT': { code: 'OCT', name: 'Common Octopus', scientificName: 'Octopus vulgaris', slug: 'octopus', image: '/webp/octopus.webp', mobile: '/webp/octopus-mobile.webp', thumb: '/webp/octopus-thumb.webp' },
  'PLE': { code: 'PLE', name: 'European Plaice', scientificName: 'Pleuronectes platessa', slug: 'plaice', image: '/webp/plaice.webp', mobile: '/webp/plaice-mobile.webp', thumb: '/webp/plaice-thumb.webp' },
  'POL': { code: 'POL', name: 'Pollack', scientificName: 'Pollachius pollachius', slug: 'pollock', image: '/webp/pollock.webp', mobile: '/webp/pollock-mobile.webp', thumb: '/webp/pollock-thumb.webp' },
  'RMU': { code: 'RMU', name: 'Red Mullet', scientificName: 'Mullus surmuletus', slug: 'red-mullet', image: '/webp/red-mullet.webp', mobile: '/webp/red-mullet-mobile.webp', thumb: '/webp/red-mullet-thumb.webp' },
  'SAI': { code: 'SAI', name: 'Saithe', scientificName: 'Pollachius virens', slug: 'saithe-pollock', image: '/webp/saithe-pollock.webp', mobile: '/webp/saithe-pollock-mobile.webp', thumb: '/webp/saithe-pollock-thumb.webp' },
  'SAN': { code: 'SAN', name: 'Sand Eel', scientificName: 'Ammodytes marinus', slug: 'sand-eel', image: '/webp/sand-eel.webp', mobile: '/webp/sand-eel-mobile.webp', thumb: '/webp/sand-eel-thumb.webp' },
  'SAR': { code: 'SAR', name: 'Sardine', scientificName: 'Sardina pilchardus', slug: 'sardine', image: '/webp/sardine.webp', mobile: '/webp/sardine-mobile.webp', thumb: '/webp/sardine-thumb.webp' },
  'SBA': { code: 'SBA', name: 'Sea Bass', scientificName: 'Dicentrarchus labrax', slug: 'bass', image: '/webp/bass.webp', mobile: '/webp/bass-mobile.webp', thumb: '/webp/bass-thumb.webp' },
  'SBR': { code: 'SBR', name: 'Sea Bream', scientificName: 'Sparus aurata', slug: 'gilthead-bream', image: '/webp/gilthead-bream.webp', mobile: '/webp/gilthead-bream-mobile.webp', thumb: '/webp/gilthead-bream-thumb.webp' },
  'SER': { code: 'SER', name: 'Spotted Bass', scientificName: 'Dicentrarchus punctatus', slug: 'spotted-bass', image: '/webp/spotted-bass.webp', mobile: '/webp/spotted-bass-mobile.webp', thumb: '/webp/spotted-bass-thumb.webp' },
  'SOL': { code: 'SOL', name: 'Dover Sole', scientificName: 'Solea solea', slug: 'dover-sole', image: '/webp/dover-sole.webp', mobile: '/webp/dover-sole-mobile.webp', thumb: '/webp/dover-sole-thumb.webp' },
  'SPA': { code: 'SPA', name: 'Parrotfish', scientificName: 'Sparisoma cretense', slug: 'parrotfish', image: '/webp/parrotfish.webp', mobile: '/webp/parrotfish-mobile.webp', thumb: '/webp/parrotfish-thumb.webp' },
  'SPR': { code: 'SPR', name: 'Sprat', scientificName: 'Sprattus sprattus', slug: 'sprat', image: '/webp/sprat.webp', mobile: '/webp/sprat-mobile.webp', thumb: '/webp/sprat-thumb.webp' },
  'SQU': { code: 'SQU', name: 'Common Squid', scientificName: 'Loligo vulgaris', slug: 'squid', image: '/webp/squid.webp', mobile: '/webp/squid-mobile.webp', thumb: '/webp/squid-thumb.webp' },
  'STR': { code: 'STR', name: 'Sea Trout', scientificName: 'Salmo trutta', slug: 'sea-trout', image: '/webp/sea-trout.webp', mobile: '/webp/sea-trout-mobile.webp', thumb: '/webp/sea-trout-thumb.webp' },
  'THO': { code: 'THO', name: 'Thornback Ray', scientificName: 'Raja clavata', slug: 'thornback-ray', image: '/webp/thornback-ray.webp', mobile: '/webp/thornback-ray-mobile.webp', thumb: '/webp/thornback-ray-thumb.webp' },
  'TUR': { code: 'TUR', name: 'Turbot', scientificName: 'Scophthalmus maximus', slug: 'turbot', image: '/webp/turbot.webp', mobile: '/webp/turbot-mobile.webp', thumb: '/webp/turbot-thumb.webp' },
  'WEE': { code: 'WEE', name: 'Greater Weever', scientificName: 'Trachinus draco', slug: 'weaver', image: '/webp/weaver.webp', mobile: '/webp/weaver-mobile.webp', thumb: '/webp/weaver-thumb.webp' },
  'WHI': { code: 'WHI', name: 'Whiting', scientificName: 'Merlangius merlangus', slug: 'whiting', image: '/webp/whiting.webp', mobile: '/webp/whiting-mobile.webp', thumb: '/webp/whiting-thumb.webp' },
  'WRA': { code: 'WRA', name: 'Ballan Wrasse', scientificName: 'Labrus bergylta', slug: 'ballan-wrasse', image: '/webp/ballan-wrasse.webp', mobile: '/webp/ballan-wrasse-mobile.webp', thumb: '/webp/ballan-wrasse-thumb.webp' },
};

export const SPECIES_IMAGES_MISSING = [] as const;
