/**
 * Auto-generated by scripts/generate-species-image-map.ts
 * Generated at: 2025-10-16T10:02:29.795Z
 */

export interface SpeciesImageInfo {
  code: string;
  name: string;
  scientificName: string | null;
  slug: string;
  image: string;
  mobile?: string | null;
  thumb?: string | null;
}

export const SPECIES_IMAGE_MAP: Record<string, SpeciesImageInfo> = {
  '2bd-bream': { code: '2bd-bream', name: 'Two-banded Seabream', scientificName: 'Diplodus vulgaris', slug: 'two-banded-seabream', image: '/webp/two-banded-seabream.webp', mobile: '/webp/two-banded-seabream-mobile.webp', thumb: '/webp/two-banded-seabream-thumb.webp' },
  'bll': { code: 'bll', name: 'Brill', scientificName: 'Scophthalmus rhombus', slug: 'brill', image: '/webp/brill.webp', mobile: '/webp/brill-mobile.webp', thumb: '/webp/brill-thumb.webp' },
  'bluefish': { code: 'bluefish', name: 'Bluefish', scientificName: 'Pomatomus saltatrix', slug: 'bluefish', image: '/webp/bluefish.webp', mobile: '/webp/bluefish-mobile.webp', thumb: '/webp/bluefish-thumb.webp' },
  'bogue': { code: 'bogue', name: 'Bogue', scientificName: 'Boops boops', slug: 'bogue', image: '/webp/bogue.webp', mobile: '/webp/bogue-mobile.webp', thumb: '/webp/bogue-thumb.webp' },
  'bonito': { code: 'bonito', name: 'Atlantic Bonito', scientificName: 'Sarda sarda', slug: 'bonito', image: '/webp/bonito.webp', mobile: '/webp/bonito-mobile.webp', thumb: '/webp/bonito-thumb.webp' },
  'brs': { code: 'brs', name: 'Black Seabream', scientificName: 'Spondyliosoma cantharus', slug: 'black-seabream', image: '/webp/black-seabream.webp', mobile: '/webp/black-seabream-mobile.webp', thumb: '/webp/black-seabream-thumb.webp' },
  'bsp': { code: 'bsp', name: 'Spotted Bass', scientificName: 'Dicentrarchus punctatus', slug: 'spotted-bass', image: '/webp/spotted-bass.webp', mobile: '/webp/spotted-bass-mobile.webp', thumb: '/webp/spotted-bass-thumb.webp' },
  'bss': { code: 'bss', name: 'Sea Bass', scientificName: 'Dicentrarchus labrax', slug: 'sea-bass', image: '/webp/sea-bass.webp', mobile: '/webp/sea-bass-mobile.webp', thumb: '/webp/sea-bass-thumb.webp' },
  'BUH': { code: 'BUH', name: 'Bull Huss', scientificName: 'Scyliorhinus stellaris', slug: 'bull-huss', image: '/webp/bull-huss.webp', mobile: '/webp/bull-huss-mobile.webp', thumb: '/webp/bull-huss-thumb.webp' },
  'chub-mack': { code: 'chub-mack', name: 'Atlantic Chub Mackerel', scientificName: 'Scomber colias', slug: 'chub-mackerel', image: '/webp/chub-mackerel.webp', mobile: '/webp/chub-mackerel-mobile.webp', thumb: '/webp/chub-mackerel-thumb.webp' },
  'CMB': { code: 'CMB', name: 'Comber', scientificName: 'Serranus cabrilla', slug: 'painted-comber', image: '/webp/painted-comber.webp', mobile: '/webp/painted-comber-mobile.webp', thumb: '/webp/painted-comber-thumb.webp' },
  'CMP': { code: 'CMP', name: 'Painted Comber', scientificName: 'Serranus scriba', slug: 'painted-comber', image: '/webp/painted-comber.webp', mobile: '/webp/painted-comber-mobile.webp', thumb: '/webp/painted-comber-thumb.webp' },
  'cod': { code: 'cod', name: 'Cod (Coastal)', scientificName: 'Gadus morhua', slug: 'cod', image: '/webp/cod.webp', mobile: '/webp/cod-mobile.webp', thumb: '/webp/cod-thumb.webp' },
  'con': { code: 'con', name: 'Conger Eel', scientificName: 'Conger conger', slug: 'conger-eel', image: '/webp/conger-eel.webp', mobile: '/webp/conger-eel-mobile.webp', thumb: '/webp/conger-eel-thumb.webp' },
  'CSH': { code: 'CSH', name: 'Common Smoothhound', scientificName: 'Mustelus mustelus', slug: 'common-smoothhound', image: '/webp/common-smoothhound.webp', mobile: '/webp/common-smoothhound-mobile.webp', thumb: '/webp/common-smoothhound-thumb.webp' },
  'cut': { code: 'cut', name: 'Common Cuttlefish', scientificName: 'Sepia officinalis', slug: 'cuttlefish', image: '/webp/cuttlefish.webp', mobile: '/webp/cuttlefish-mobile.webp', thumb: '/webp/cuttlefish-thumb.webp' },
  'dab': { code: 'dab', name: 'Dab', scientificName: 'Limanda limanda', slug: 'dab', image: '/webp/dab.webp', mobile: '/webp/dab-mobile.webp', thumb: '/webp/dab-thumb.webp' },
  'dex': { code: 'dex', name: 'Dentex', scientificName: 'Dentex dentex', slug: 'dentex', image: '/webp/dentex.webp', mobile: '/webp/dentex-mobile.webp', thumb: '/webp/dentex-thumb.webp' },
  'dusk-group': { code: 'dusk-group', name: 'Dusky Grouper', scientificName: 'Epinephelus marginatus', slug: 'dusky-grouper', image: '/webp/dusky-grouper.webp', mobile: '/webp/dusky-grouper-mobile.webp', thumb: '/webp/dusky-grouper-thumb.webp' },
  'euro-cuda': { code: 'euro-cuda', name: 'European Barracuda', scientificName: 'Sphyraena sphyraena', slug: 'barracuda', image: '/webp/barracuda.webp', mobile: '/webp/barracuda-mobile.webp', thumb: '/webp/barracuda-thumb.webp' },
  'fgm': { code: 'fgm', name: 'Flathead Grey Mullet', scientificName: 'Mugil cephalus', slug: 'flathead-grey-mullet', image: '/webp/flathead-grey-mullet.webp', mobile: '/webp/flathead-grey-mullet-mobile.webp', thumb: '/webp/flathead-grey-mullet-thumb.webp' },
  'fle': { code: 'fle', name: 'Flounder', scientificName: 'Platichthys flesus', slug: 'flounder', image: '/webp/flounder.webp', mobile: '/webp/flounder-mobile.webp', thumb: '/webp/flounder-thumb.webp' },
  'gaj': { code: 'gaj', name: 'Greater Amberjack', scientificName: 'Seriola dumerili', slug: 'greater-amberjack', image: '/webp/greater-amberjack.webp', mobile: '/webp/greater-amberjack-mobile.webp', thumb: '/webp/greater-amberjack-thumb.webp' },
  'gar': { code: 'gar', name: 'Garfish (Needlefish)', scientificName: 'Belone belone', slug: 'garfish', image: '/webp/garfish.webp', mobile: '/webp/garfish-mobile.webp', thumb: '/webp/garfish-thumb.webp' },
  'GGR': { code: 'GGR', name: 'Grey Gurnard', scientificName: 'Eutrigla gurnardus', slug: 'grey-gurnard', image: '/webp/grey-gurnard.webp', mobile: '/webp/grey-gurnard-mobile.webp', thumb: '/webp/grey-gurnard-thumb.webp' },
  'gug': { code: 'gug', name: 'Tub Gurnard', scientificName: 'Chelidonichthys lucerna', slug: 'tub-gurnard', image: '/webp/tub-gurnard.webp', mobile: '/webp/tub-gurnard-mobile.webp', thumb: '/webp/tub-gurnard-thumb.webp' },
  'GUR': { code: 'GUR', name: 'Red Gurnard', scientificName: 'Chelidonichthys cuculus', slug: 'red-gurnard', image: '/webp/red-gurnard.webp', mobile: '/webp/red-gurnard-mobile.webp', thumb: '/webp/red-gurnard-thumb.webp' },
  'had': { code: 'had', name: 'Haddock', scientificName: 'Melanogrammus aeglefinus', slug: 'haddock', image: '/webp/haddock.webp', mobile: '/webp/haddock-mobile.webp', thumb: '/webp/haddock-thumb.webp' },
  'her': { code: 'her', name: 'Herring', scientificName: 'Clupea harengus', slug: 'herring', image: '/webp/herring.webp', mobile: '/webp/herring-mobile.webp', thumb: '/webp/herring-thumb.webp' },
  'hom': { code: 'hom', name: 'Horse Mackerel', scientificName: 'Trachurus trachurus', slug: 'horse-mackerel', image: '/webp/horse-mackerel.webp', mobile: '/webp/horse-mackerel-mobile.webp', thumb: '/webp/horse-mackerel-thumb.webp' },
  'jod': { code: 'jod', name: 'John Dory', scientificName: 'Zeus faber', slug: 'john-dory', image: '/webp/john-dory.webp', mobile: '/webp/john-dory-mobile.webp', thumb: '/webp/john-dory-thumb.webp' },
  'ldb': { code: 'ldb', name: 'Megrim', scientificName: 'Lepidorhombus whiffiagonis', slug: 'megrim', image: '/webp/megrim.webp', mobile: '/webp/megrim-mobile.webp', thumb: '/webp/megrim-thumb.webp' },
  'leerfish': { code: 'leerfish', name: 'Leerfish', scientificName: 'Lichia amia', slug: 'leerfish', image: '/webp/leerfish.webp', mobile: '/webp/leerfish-mobile.webp', thumb: '/webp/leerfish-thumb.webp' },
  'lin': { code: 'lin', name: 'Common Ling', scientificName: 'Molva molva', slug: 'ling', image: '/webp/ling.webp', mobile: '/webp/ling-mobile.webp', thumb: '/webp/ling-thumb.webp' },
  'lta': { code: 'lta', name: 'Little Tunny', scientificName: 'Euthynnus alletteratus', slug: 'little-tunny', image: '/webp/little-tunny.webp', mobile: '/webp/little-tunny-mobile.webp', thumb: '/webp/little-tunny-thumb.webp' },
  'mac': { code: 'mac', name: 'Mackerel', scientificName: 'Scomber scombrus', slug: 'mackerel', image: '/webp/mackerel.webp', mobile: '/webp/mackerel-mobile.webp', thumb: '/webp/mackerel-thumb.webp' },
  'meagre': { code: 'meagre', name: 'Meagre', scientificName: 'Argyrosomus regius', slug: 'meagre', image: '/webp/meagre.webp', mobile: '/webp/meagre-mobile.webp', thumb: '/webp/meagre-thumb.webp' },
  'med-scad': { code: 'med-scad', name: 'Mediterranean Scad', scientificName: 'Trachurus mediterraneus', slug: 'mediterranean-scad', image: '/webp/mediterranean-scad.webp', mobile: '/webp/mediterranean-scad-mobile.webp', thumb: '/webp/mediterranean-scad-thumb.webp' },
  'mug': { code: 'mug', name: 'Grey Mullet', scientificName: 'Chelon labrosus', slug: 'grey-mullet', image: '/webp/grey-mullet.webp', mobile: '/webp/grey-mullet-mobile.webp', thumb: '/webp/grey-mullet-thumb.webp' },
  'mul': { code: 'mul', name: 'Red Mullet', scientificName: 'Mullus surmuletus', slug: 'red-mullet', image: '/webp/red-mullet.webp', mobile: '/webp/red-mullet-mobile.webp', thumb: '/webp/red-mullet-thumb.webp' },
  'oct': { code: 'oct', name: 'Common Octopus', scientificName: 'Octopus vulgaris', slug: 'common-octopus', image: '/webp/common-octopus.webp', mobile: '/webp/common-octopus-mobile.webp', thumb: '/webp/common-octopus-thumb.webp' },
  'pandora': { code: 'pandora', name: 'Common Pandora', scientificName: 'Pagellus erythrinus', slug: 'common-pandora', image: '/webp/common-pandora.webp', mobile: '/webp/common-pandora-mobile.webp', thumb: '/webp/common-pandora-thumb.webp' },
  'par': { code: 'par', name: 'Parrotfish', scientificName: 'Sparisoma cretense', slug: 'parrotfish', image: '/webp/parrotfish.webp', mobile: '/webp/parrotfish-mobile.webp', thumb: '/webp/parrotfish-thumb.webp' },
  'PIC': { code: 'PIC', name: 'Picarel', scientificName: 'Spicara smaris', slug: 'picarel', image: '/webp/picarel.webp', mobile: '/webp/picarel-mobile.webp', thumb: '/webp/picarel-thumb.webp' },
  'pil': { code: 'pil', name: 'Sardine', scientificName: 'Sardina pilchardus', slug: 'sardine', image: '/webp/sardine.webp', mobile: '/webp/sardine-mobile.webp', thumb: '/webp/sardine-thumb.webp' },
  'ple': { code: 'ple', name: 'Plaice', scientificName: 'Pleuronectes platessa', slug: 'plaice', image: '/webp/plaice.webp', mobile: '/webp/plaice-mobile.webp', thumb: '/webp/plaice-thumb.webp' },
  'pok': { code: 'pok', name: 'Saithe (Pollachius virens)', scientificName: 'Pollachius virens', slug: 'saithe', image: '/webp/saithe.webp', mobile: '/webp/saithe-mobile.webp', thumb: '/webp/saithe-thumb.webp' },
  'pol': { code: 'pol', name: 'Pollack', scientificName: 'Pollachius pollachius', slug: 'pollack', image: '/webp/pollack.webp', mobile: '/webp/pollack-mobile.webp', thumb: '/webp/pollack-thumb.webp' },
  'red-porgy': { code: 'red-porgy', name: 'Red Porgy', scientificName: 'Pagrus pagrus', slug: 'red-porgy', image: '/webp/red-porgy.webp', mobile: '/webp/red-porgy-mobile.webp', thumb: '/webp/red-porgy-thumb.webp' },
  'red-scorp': { code: 'red-scorp', name: 'Red Scorpionfish', scientificName: 'Scorpaena scrofa', slug: 'red-scorpionfish', image: '/webp/red-scorpionfish.webp', mobile: '/webp/red-scorpionfish-mobile.webp', thumb: '/webp/red-scorpionfish-thumb.webp' },
  'rjc': { code: 'rjc', name: 'Thornback Ray', scientificName: 'Raja clavata', slug: 'thornback-ray', image: '/webp/thornback-ray.webp', mobile: '/webp/thornback-ray-mobile.webp', thumb: '/webp/thornback-ray-thumb.webp' },
  'RJM': { code: 'RJM', name: 'Spotted Ray', scientificName: 'Raja montagui', slug: 'spotted-ray', image: '/webp/spotted-ray.webp', mobile: '/webp/spotted-ray-mobile.webp', thumb: '/webp/spotted-ray-thumb.webp' },
  'RME': { code: 'RME', name: 'Small-eyed Ray', scientificName: 'Raja microocellata', slug: 'small-eyed-ray', image: '/webp/small-eyed-ray.webp', mobile: '/webp/small-eyed-ray-mobile.webp', thumb: '/webp/small-eyed-ray-thumb.webp' },
  'RUN': { code: 'RUN', name: 'Undulate Ray', scientificName: 'Raja undulata', slug: 'undulate-ray', image: '/webp/undulate-ray.webp', mobile: '/webp/undulate-ray-mobile.webp', thumb: '/webp/undulate-ray-thumb.webp' },
  'sadd-bream': { code: 'sadd-bream', name: 'Saddled Seabream', scientificName: 'Oblada melanura', slug: 'saddled-seabream', image: '/webp/saddled-seabream.webp', mobile: '/webp/saddled-seabream-mobile.webp', thumb: '/webp/saddled-seabream-thumb.webp' },
  'sai': { code: 'sai', name: 'Saithe/Pollock', scientificName: 'Saithe/Pollock', slug: 'saithe-pollock', image: '/webp/saithe-pollock.webp', mobile: '/webp/saithe-pollock-mobile.webp', thumb: '/webp/saithe-pollock-thumb.webp' },
  'SAL': { code: 'SAL', name: 'Salema (Saupe)', scientificName: 'Sarpa salpa', slug: 'salema', image: '/webp/salema.webp', mobile: '/webp/salema-mobile.webp', thumb: '/webp/salema-thumb.webp' },
  'san': { code: 'san', name: 'Sand Eel', scientificName: 'Ammodytes tobianus', slug: 'sand-eel', image: '/webp/sand-eel.webp', mobile: '/webp/sand-eel-mobile.webp', thumb: '/webp/sand-eel-thumb.webp' },
  'sba': { code: 'sba', name: 'Sea Bream (Dorada)', scientificName: 'Sparus aurata', slug: 'gilthead-seabream', image: '/webp/gilthead-seabream.webp', mobile: '/webp/gilthead-seabream-mobile.webp', thumb: '/webp/gilthead-seabream-thumb.webp' },
  'sbg': { code: 'sbg', name: 'Gilthead Seabream', scientificName: 'Gilthead Seabream', slug: 'gilthead-seabream', image: '/webp/gilthead-seabream.webp', mobile: '/webp/gilthead-seabream-mobile.webp', thumb: '/webp/gilthead-seabream-thumb.webp' },
  'sbr': { code: 'sbr', name: 'Red Seabream', scientificName: 'Pagellus bogaraveo', slug: 'red-seabream', image: '/webp/red-seabream.webp', mobile: '/webp/red-seabream-mobile.webp', thumb: '/webp/red-seabream-thumb.webp' },
  'scy': { code: 'scy', name: 'Small-spotted Catshark', scientificName: 'Scyliorhinus canicula', slug: 'small-spotted-catshark', image: '/webp/small-spotted-catshark.webp', mobile: '/webp/small-spotted-catshark-mobile.webp', thumb: '/webp/small-spotted-catshark-thumb.webp' },
  'sol': { code: 'sol', name: 'Dover Sole', scientificName: 'Solea solea', slug: 'dover-sole', image: '/webp/dover-sole.webp', mobile: '/webp/dover-sole-mobile.webp', thumb: '/webp/dover-sole-thumb.webp' },
  'spr': { code: 'spr', name: 'Sprat', scientificName: 'Sprattus sprattus', slug: 'sprat', image: '/webp/sprat.webp', mobile: '/webp/sprat-mobile.webp', thumb: '/webp/sprat-thumb.webp' },
  'sqc': { code: 'sqc', name: 'Common Squid', scientificName: 'Loligo vulgaris', slug: 'squid', image: '/webp/squid.webp', mobile: '/webp/squid-mobile.webp', thumb: '/webp/squid-thumb.webp' },
  'SSH': { code: 'SSH', name: 'Starry Smoothhound', scientificName: 'Mustelus asterias', slug: 'starry-smoothhound', image: '/webp/starry-smoothhound.webp', mobile: '/webp/starry-smoothhound-mobile.webp', thumb: '/webp/starry-smoothhound-thumb.webp' },
  'trs': { code: 'trs', name: 'Sea Trout', scientificName: 'Salmo trutta', slug: 'sea-trout', image: '/webp/sea-trout.webp', mobile: '/webp/sea-trout-mobile.webp', thumb: '/webp/sea-trout-thumb.webp' },
  'tur': { code: 'tur', name: 'Turbot (Small)', scientificName: 'Scophthalmus maximus', slug: 'turbot', image: '/webp/turbot.webp', mobile: '/webp/turbot-mobile.webp', thumb: '/webp/turbot-thumb.webp' },
  'wee': { code: 'wee', name: 'Greater Weever', scientificName: 'Trachinus draco', slug: 'greater-weever', image: '/webp/greater-weever.webp', mobile: '/webp/greater-weever-mobile.webp', thumb: '/webp/greater-weever-thumb.webp' },
  'whg': { code: 'whg', name: 'Whiting', scientificName: 'Merlangius merlangus', slug: 'whiting', image: '/webp/whiting.webp', mobile: '/webp/whiting-mobile.webp', thumb: '/webp/whiting-thumb.webp' },
  'whit-group': { code: 'whit-group', name: 'White Grouper', scientificName: 'Epinephelus aeneus', slug: 'white-grouper', image: '/webp/white-grouper.webp', mobile: '/webp/white-grouper-mobile.webp', thumb: '/webp/white-grouper-thumb.webp' },
  'wht-bream': { code: 'wht-bream', name: 'White Seabream', scientificName: 'Diplodus sargus', slug: 'white-seabream', image: '/webp/white-seabream.webp', mobile: '/webp/white-seabream-mobile.webp', thumb: '/webp/white-seabream-thumb.webp' },
  'wra': { code: 'wra', name: 'Wrasse (various)', scientificName: 'Labridae spp.', slug: 'wrasse', image: '/webp/wrasse.webp', mobile: '/webp/wrasse-mobile.webp', thumb: '/webp/wrasse-thumb.webp' },
  'wrb': { code: 'wrb', name: 'Ballan Wrasse', scientificName: 'Labrus bergylta', slug: 'ballan-wrasse', image: '/webp/ballan-wrasse.webp', mobile: '/webp/ballan-wrasse-mobile.webp', thumb: '/webp/ballan-wrasse-thumb.webp' },
  'wrc': { code: 'wrc', name: 'Cuckoo Wrasse', scientificName: 'Labrus mixtus', slug: 'cuckoo-wrasse', image: '/webp/cuckoo-wrasse.webp', mobile: '/webp/cuckoo-wrasse-mobile.webp', thumb: '/webp/cuckoo-wrasse-thumb.webp' },
  'WRG': { code: 'WRG', name: 'Goldsinny Wrasse', scientificName: 'Ctenolabrus rupestris', slug: 'goldsinny-wrasse', image: '/webp/goldsinny-wrasse.webp', mobile: '/webp/goldsinny-wrasse-mobile.webp', thumb: '/webp/goldsinny-wrasse-thumb.webp' },
  'WRK': { code: 'WRK', name: 'Corkwing Wrasse', scientificName: 'Symphodus melops', slug: 'corkwing-wrasse', image: '/webp/corkwing-wrasse.webp', mobile: '/webp/corkwing-wrasse-mobile.webp', thumb: '/webp/corkwing-wrasse-thumb.webp' },
  'WRO': { code: 'WRO', name: 'Rock Cook', scientificName: 'Centrolabrus exoletus', slug: 'rock-cook', image: '/webp/rock-cook.webp', mobile: '/webp/rock-cook-mobile.webp', thumb: '/webp/rock-cook-thumb.webp' },
  'yel-cuda': { code: 'yel-cuda', name: 'Yellowmouth Barracuda', scientificName: 'Sphyraena viridensis', slug: 'yellowmouth-barracuda', image: '/webp/yellowmouth-barracuda.webp', mobile: '/webp/yellowmouth-barracuda-mobile.webp', thumb: '/webp/yellowmouth-barracuda-thumb.webp' },
};

export const SPECIES_IMAGES_MISSING = [

] as const;
