import { promises as fs } from 'fs';
import path from 'path';
import { SPECIES_IMAGE_MAP } from '../data/speciesImageMap';

interface BlurPlaceholder {
  code: string;
  blurDataURL: string;
}

async function main() {
  console.log('📝 Updating speciesImageMap.ts with blur placeholders...\n');

  // Load blur placeholders
  const blurPlaceholdersPath = path.join(process.cwd(), 'data', 'blur-placeholders.json');
  const blurData: BlurPlaceholder[] = JSON.parse(
    await fs.readFile(blurPlaceholdersPath, 'utf-8')
  );

  // Create a map for quick lookup
  const blurMap = new Map<string, string>();
  blurData.forEach(({ code, blurDataURL }) => {
    blurMap.set(code, blurDataURL);
  });

  console.log(`✅ Loaded ${blurData.length} blur placeholders`);

  // Generate updated TypeScript file
  const lines: string[] = [
    '/**',
    ' * Auto-generated by scripts/update-species-image-map-with-blur.ts',
    ` * Generated at: ${new Date().toISOString()}`,
    ' */',
    '',
    'export interface SpeciesImageInfo {',
    '  code: string;',
    '  name: string;',
    '  scientificName: string | null;',
    '  slug: string;',
    '  image: string;',
    '  mobile?: string | null;',
    '  thumb?: string | null;',
    '  blurDataURL?: string;',
    '}',
    '',
    'export const SPECIES_IMAGE_MAP: Record<string, SpeciesImageInfo> = {',
  ];

  let matched = 0;
  let unmatched = 0;

  for (const [code, info] of Object.entries(SPECIES_IMAGE_MAP)) {
    const blurDataURL = blurMap.get(code);

    if (blurDataURL) {
      matched++;
      lines.push(
        `  '${code}': { ` +
        `code: '${code}', ` +
        `name: '${info.name}', ` +
        `scientificName: ${info.scientificName ? `'${info.scientificName}'` : 'null'}, ` +
        `slug: '${info.slug}', ` +
        `image: '${info.image}', ` +
        `mobile: ${info.mobile ? `'${info.mobile}'` : 'null'}, ` +
        `thumb: ${info.thumb ? `'${info.thumb}'` : 'null'}, ` +
        `blurDataURL: '${blurDataURL}' },`
      );
    } else {
      unmatched++;
      // Keep original entry without blur placeholder
      lines.push(
        `  '${code}': { ` +
        `code: '${code}', ` +
        `name: '${info.name}', ` +
        `scientificName: ${info.scientificName ? `'${info.scientificName}'` : 'null'}, ` +
        `slug: '${info.slug}', ` +
        `image: '${info.image}', ` +
        `mobile: ${info.mobile ? `'${info.mobile}'` : 'null'}, ` +
        `thumb: ${info.thumb ? `'${info.thumb}'` : 'null'} },`
      );
    }
  }

  lines.push('};');
  lines.push(''); // trailing newline

  const content = lines.join('\n');

  // Write updated file
  const outputPath = path.join(process.cwd(), 'data', 'speciesImageMap.ts');
  await fs.writeFile(outputPath, content, 'utf-8');

  console.log(`✅ Updated ${matched} species with blur placeholders`);
  console.log(`⚠️  ${unmatched} species without blur placeholders`);
  console.log(`✨ File saved to ${outputPath}`);
}

main().catch(console.error);
