export type PlantImageSizes = {
  emoji: string;
  medium: string;
  lg: string;
  xl?: string;
};

export type PlantImageMap = Record<string, PlantImageSizes & { source?: string }>;

// Generated by `scripts/optimize-plant-images.py`
// Public paths relative to Next.js `public/`.
import plantImageMapData from '../../public/grow/plants/plant-image-map.json';

export const PLANT_IMAGE_MAP: PlantImageMap = plantImageMapData as PlantImageMap;

export function getPlantImage(key: string, size: keyof PlantImageSizes = 'medium'): string | null {
  const entry = PLANT_IMAGE_MAP[key];
  if (!entry) return null;
  return entry[size] ?? null;
}
