-- Migration: Add pest resilience scores and notes to all 458 plant species
-- Score: 1=Very vulnerable, 2=Somewhat vulnerable, 3=Average, 4=Good resilience, 5=Highly resilient

BEGIN;

-- 1. Add columns
ALTER TABLE plant_species ADD COLUMN IF NOT EXISTS pest_resilience_score SMALLINT;
ALTER TABLE plant_species ADD COLUMN IF NOT EXISTS pest_resilience_note TEXT;
ALTER TABLE plant_species ADD CONSTRAINT chk_pest_resilience_score CHECK (pest_resilience_score BETWEEN 1 AND 5);

-- ============================================================
-- FRUIT (soft fruit)
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Big bud mite and gall midge can be troublesome; choose resistant cultivars.' WHERE scientific_name = 'Ribes nigrum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Sawfly caterpillars can strip leaves quickly; inspect undersides regularly.' WHERE scientific_name = 'Ribes rubrum';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Gooseberry sawfly and American mildew are the main threats; check leaves from late spring.' WHERE scientific_name = 'Ribes uva-crispa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Slugs target young plants and birds love the fruit; otherwise fairly tough.' WHERE scientific_name = 'Fragaria vesca';

-- ============================================================
-- FRUIT TREES
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Apple scab, codling moth, and woolly aphid are common; regular monitoring needed.' WHERE scientific_name = 'Malus domestica';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Bacterial canker and peach leaf curl are risks; generally less pest-prone than peach.' WHERE scientific_name = 'Prunus armeniaca';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free and disease-resistant once established.' WHERE scientific_name = 'Aronia melanocarpa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; nitrogen-fixing and naturally robust.' WHERE scientific_name = 'Elaeagnus umbellata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few serious pests; squirrels may take nuts before you do.' WHERE slug = 'fruit-black-walnut';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Mealybugs and scale insects can appear under cover; relatively pest-free outdoors in mild areas.' WHERE scientific_name = 'Annona cherimola';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Black cherry aphid and bacterial canker are the main risks; birds will take fruit.' WHERE scientific_name = 'Prunus cerasus';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Black cherry aphid, bacterial canker, and birds are persistent problems.' WHERE scientific_name = 'Prunus avium';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; generally very hardy and low-maintenance.' WHERE scientific_name = 'Crataegus pinnatifida';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a tough, resilient small tree.' WHERE scientific_name = 'Cornus mas';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Plum moth and silver leaf disease are the main concerns.' WHERE scientific_name = 'Prunus domestica subsp. insititia';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; elder aphid may cluster on shoots but rarely causes lasting damage.' WHERE slug = 'fruit-elder';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; elder aphid may cluster on shoots but rarely causes lasting damage.' WHERE slug = 'fruit-elder-black-lace';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems in cool climates; scale insects possible under glass.' WHERE scientific_name = 'Acca sellowiana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free outdoors; red spider mite can appear under glass.' WHERE scientific_name = 'Ficus carica';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Plum moth and silver leaf can affect it; similar pest profile to plums.' WHERE scientific_name = 'Prunus domestica subsp. italica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests in temperate climates; generally robust.' WHERE scientific_name = 'Psidium cattleianum';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free and very tough once established.' WHERE slug = 'fruit-hackberry';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; cats may nibble young plants due to actinidine content.' WHERE scientific_name = 'Actinidia arguta' AND slug = 'fruit-hardy-kiwi';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Nut weevil and squirrels are the main problems; big bud mite occasionally.' WHERE slug = 'fruit-hazelnut';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a tough, low-maintenance fruiting shrub.' WHERE slug = 'fruit-honeyberry-treeform';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; an unusual and resilient hybrid tree.' WHERE scientific_name = '× Sorbopyrus auricularis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Combines vigour of parents; few pest issues reported.' WHERE scientific_name = 'Ribes × nidigrolaria';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters pests; virtually trouble-free.' WHERE slug = 'fruit-juniper-berry';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Scale insects, citrus leaf miner, and red spider mite under glass; needs vigilance.' WHERE scientific_name = 'Citrus limon';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Scale insects and mealybugs under glass; generally healthy outdoors in warm climates.' WHERE scientific_name = 'Citrus aurantiifolia';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; fire blight possible but uncommon.' WHERE scientific_name = 'Eriobotrya japonica';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Scale insects and citrus leaf miner may appear; similar to other citrus.' WHERE scientific_name = 'Citrus reticulata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; a tough native hawthorn relative.' WHERE scientific_name = 'Crataegus aestivalis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; an underrated and trouble-free fruit tree.' WHERE scientific_name = 'Mespilus germanica';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Plum moth and silver leaf are possible; similar to other plums.' WHERE scientific_name = 'Prunus domestica subsp. syriaca';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; birds take berries but the tree is resilient.' WHERE slug = 'fruit-mountain-ash';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems once established; birds enjoy the fruit.' WHERE scientific_name = 'Morus nigra';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; fast-growing and resilient.' WHERE scientific_name = 'Morus alba';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Peach leaf curl is the main threat; aphids and brown rot also common.' WHERE scientific_name = 'Prunus persica var. nucipersica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free outdoors; scale insects may appear in warm climates.' WHERE scientific_name = 'Olea europaea';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Scale insects and citrus leaf miner possible; similar pest profile to lemon.' WHERE scientific_name = 'Citrus x sinensis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; few insects bother it thanks to its chemistry.' WHERE scientific_name = 'Asimina triloba';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Peach leaf curl is almost inevitable without protection; aphids and brown rot also common.' WHERE scientific_name = 'Prunus persica';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Pear midge, pear blister mite, and fire blight can all be problematic.' WHERE scientific_name = 'Pyrus communis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues in temperate climates; generally trouble-free.' WHERE scientific_name = 'Diospyros kaki';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Plum moth, aphids, and silver leaf disease are the main concerns.' WHERE scientific_name = 'Prunus domestica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems in cool climates; scale insects possible in warmer areas.' WHERE scientific_name = 'Punica granatum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; adapted to harsh Australian conditions.' WHERE scientific_name = 'Santalum acuminatum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Codling moth and brown rot can affect fruit; leaf blight occasionally.' WHERE scientific_name = 'Cydonia oblonga';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Very few pest or disease issues; tough and productive.' WHERE scientific_name = 'Amelanchier alnifolia';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; nitrogen-fixing and extremely tough.' WHERE scientific_name = 'Hippophae rhamnoides';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; birds may take fruit but the tree is trouble-free.' WHERE slug = 'fruit-serviceberry';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Chestnut blight is devastating where present; ink disease and weevils also a concern.' WHERE slug = 'fruit-sweet-chestnut';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Walnut blotch and walnut aphid are occasional problems; squirrels take nuts.' WHERE slug = 'fruit-walnut';

-- ============================================================
-- HERBS
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters most pests; virtually trouble-free.' WHERE slug = 'anise-hyssop';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; aphids occasionally but rarely a problem.' WHERE scientific_name = 'Fagopyrum esculentum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests bother it; robust and vigorous.' WHERE slug = 'burdock';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic oils strongly deter pests; virtually pest-free.' WHERE slug = 'catmint';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; may attract some aphids but generally trouble-free.' WHERE slug = 'chervil';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Onion family chemistry deters most pests; occasionally gets rust.' WHERE slug = 'chive';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; vigorous spreader with no significant pest issues.' WHERE scientific_name = 'Tussilago farfara';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can be an issue; bolts quickly so pests rarely have time to build up.' WHERE slug = 'coriander';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic mint; virtually pest-free.' WHERE scientific_name = 'Mentha requienii';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; vigorous cover crop.' WHERE scientific_name = 'Trifolium incarnatum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aphids occasionally cluster on flower heads but rarely cause harm.' WHERE slug = 'dill';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strong aromatic oils repel virtually all pests.' WHERE scientific_name = 'Dysphania ambrosioides';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; swallowtail butterfly caterpillars may feed on it but rarely cause damage.' WHERE slug = 'fennel-perennial';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aphids occasionally but generally pest-resistant due to aromatic compounds.' WHERE slug = 'feverfew';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; slugs may nibble young leaves but it is generally robust.' WHERE slug = 'garden-sorrel';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; celery fly larvae occasionally mine leaves.' WHERE scientific_name = 'Angelica archangelica';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters most pests; virtually trouble-free.' WHERE slug = 'herb-anise-hyssop';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and slugs target it; also susceptible to downy mildew in cool wet weather.' WHERE slug = 'herb-basil-greek';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Prone to aphids, slugs, and downy mildew; needs warmth and good airflow.' WHERE slug = 'herb-basil-sweet';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'More pest-resistant than sweet basil but still vulnerable to aphids and downy mildew.' WHERE slug = 'herb-basil-thai';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic evergreen foliage deters virtually all pests; scale insects very rare.' WHERE scientific_name = 'Laurus nobilis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; attracts beneficial insects which helps nearby plants.' WHERE slug = 'herb-borage';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aphids occasionally; generally robust and self-sowing.' WHERE slug = 'herb-calendula';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic oils strongly deter pests; virtually pest-free.' WHERE slug = 'herb-catmint-ornamental';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; deters pests naturally. Cats may flatten it though.' WHERE scientific_name = 'Nepeta cataria';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; aphids occasionally but rarely problematic.' WHERE scientific_name = 'Matricaria chamomilla';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; a tough ground-cover herb.' WHERE scientific_name = 'Chamaemelum nobile';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; may attract some aphids but generally trouble-free.' WHERE slug = 'herb-chervil';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; rust may appear in humid conditions.' WHERE slug = 'herb-chives-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; a vigorous plant that outgrows most problems.' WHERE slug = 'herb-comfrey';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can be an issue; bolts quickly so pests rarely build up.' WHERE slug = 'herb-coriander-leaf';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic foliage deters most pests; aphids occasionally on flower heads.' WHERE slug = 'herb-dill-leaf';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; swallowtail caterpillars may feed on it but damage is minimal.' WHERE slug = 'herb-fennel-leaf';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; slugs may nibble in wet conditions.' WHERE scientific_name = 'Centella asiatica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic oils provide good pest resistance; more resilient than sweet basil.' WHERE scientific_name = 'Ocimum tenuiflorum';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually pest-free.' WHERE slug = 'herb-hyssop';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Vigorous spreader with aromatic foliage; virtually pest-free.' WHERE slug = 'herb-lemon-balm';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic oils deter most pests; whitefly may appear under glass.' WHERE scientific_name = 'Aloysia citriodora';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; celery leaf miner occasionally but rarely serious.' WHERE scientific_name = 'Levisticum officinale';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic oils deter most pests; generally trouble-free.' WHERE scientific_name = 'Origanum majorana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; a tough and vigorous plant.' WHERE scientific_name = 'Althaea officinalis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Prickly and aromatic; virtually nothing eats it.' WHERE scientific_name = 'Silybum marianum';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Intensely aromatic; virtually pest-free and spreads vigorously.' WHERE scientific_name = 'Mentha × piperita';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Intensely aromatic; virtually pest-free. Mint rust very occasionally.' WHERE scientific_name = 'Mentha spicata';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually pest-free.' WHERE slug = 'herb-oregano';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually pest-free.' WHERE slug = 'herb-oregano-greek';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Carrot fly can be a problem as it is in the same family; use fleece barriers.' WHERE slug = 'herb-parsley-curly';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Carrot fly larvae may tunnel roots; aphids occasionally on foliage.' WHERE slug = 'herb-parsley-flat';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Highly aromatic woody herb; virtually pest-free once established.' WHERE scientific_name = 'Salvia rosmarinus';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters virtually all pests; very tough.' WHERE slug = 'herb-sage-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic and tender perennial; whitefly may appear under glass.' WHERE scientific_name = 'Salvia elegans';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters virtually all pests; very tough.' WHERE slug = 'herb-sage-purple';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually pest-free.' WHERE scientific_name = 'Satureja hortensis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Woody aromatic herb; virtually pest-free.' WHERE scientific_name = 'Satureja montana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a low-maintenance medicinal herb.' WHERE scientific_name = 'Scutellaria lateriflora';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; slugs may nibble young leaves but it recovers well.' WHERE slug = 'herb-sorrel-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally a tough, low-maintenance plant.' WHERE scientific_name = 'Hypericum perforatum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Whitefly and aphids can be problematic under glass; fairly pest-free outdoors.' WHERE scientific_name = 'Stevia rebaudiana';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free ground cover; coumarin content deters most insects.' WHERE scientific_name = 'Galium odoratum';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually nothing eats it.' WHERE slug = 'herb-tansy';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic foliage deters most pests; generally trouble-free.' WHERE scientific_name = 'Artemisia dracunculus';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic oils deter most pests; virtually trouble-free.' WHERE slug = 'herb-thyme-common';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic oils deter most pests; virtually trouble-free.' WHERE scientific_name = 'Thymus × citriodorus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; aphids occasionally but rarely an issue.' WHERE slug = 'herb-valerian';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Bitter aromatic compounds deter virtually all pests.' WHERE slug = 'herb-wormwood';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually pest-free.' WHERE slug = 'hyssop';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a fast-growing cover crop.' WHERE scientific_name = 'Lolium multiflorum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; a robust native wildflower.' WHERE scientific_name = 'Eutrochium purpureum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a tough native wildflower.' WHERE scientific_name = 'Anthyllis vulneraria';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Intensely aromatic; virtually pest-free and spreads vigorously.' WHERE slug = 'lemon-balm';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids may colonise; lupin aphid specifically targets lupins.' WHERE scientific_name = 'Lupinus luteus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic foliage deters most pests; powdery mildew occasionally in late summer.' WHERE slug = 'monarda';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic foliage deters most pests; more mildew-resistant than M. didyma.' WHERE scientific_name = 'Monarda fistulosa';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Bitter aromatic compounds deter virtually all pests.' WHERE scientific_name = 'Artemisia vulgaris';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Very few pests bother it; tough and woolly-leaved.' WHERE scientific_name = 'Verbascum thapsus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a useful cover crop and green manure.' WHERE scientific_name = 'Avena sativa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Carrot fly is a risk as it is in the Apiaceae family; aphids occasionally.' WHERE slug = 'parsley';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Intensely aromatic mint; virtually pest-free.' WHERE scientific_name = 'Mentha pulegium';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can colonise stems; generally fairly robust once established.' WHERE scientific_name = 'Lathyrus latifolius';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; excellent pollinator plant and green manure.' WHERE scientific_name = 'Phacelia tanacetifolia';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a tough nitrogen-fixing cover crop.' WHERE scientific_name = 'Trifolium pratense';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic and toxic to many insects; virtually pest-free.' WHERE slug = 'rue';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very vigorous with few pest problems; outgrows most issues.' WHERE scientific_name = 'Symphytum × uplandicum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a tough cereal cover crop.' WHERE scientific_name = 'Secale cereale';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a tough native ground-cover herb.' WHERE scientific_name = 'Prunella vulgaris';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; slugs may nibble but it recovers quickly.' WHERE slug = 'sheep-sorrel';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; slugs may nibble but it recovers quickly.' WHERE slug = 'sheep-sorrel-2';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Bitter aromatic compounds deter virtually all pests.' WHERE scientific_name = 'Artemisia abrotanum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a vigorous nitrogen-fixing cover crop.' WHERE scientific_name = 'Melilotus officinalis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Strongly aromatic; virtually nothing eats it.' WHERE slug = 'tansy';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic oils deter most pests; virtually trouble-free.' WHERE scientific_name = 'Thymus serpyllum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; aphids occasionally but rarely an issue.' WHERE slug = 'valerian';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough native wildflower.' WHERE scientific_name = 'Verbena hastata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; a useful nitrogen-fixing cover crop.' WHERE scientific_name = 'Vicia sativa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; tough nitrogen-fixer and ground cover.' WHERE scientific_name = 'Trifolium repens';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic woolly foliage deters virtually all pests.' WHERE scientific_name = 'Thymus pseudolanuginosus';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Bitter aromatic compounds deter virtually all pests.' WHERE slug = 'wormwood';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough and vigorous wildflower.' WHERE scientific_name = 'Rumex crispus';

-- ============================================================
-- ORNAMENTALS
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free ground cover; vine weevil larvae may eat roots in pots.' WHERE scientific_name = 'Ajuga reptans';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Flea beetles can riddle leaves with holes; slugs also target seedlings.' WHERE scientific_name = 'Lobularia maritima';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems once established; generally tough and drought-tolerant.' WHERE scientific_name = 'Aurinia saxatilis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; oleander aphid may appear but rarely causes serious damage.' WHERE scientific_name = 'Asclepias tuberosa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Vine weevil can damage roots in pots; powdery mildew in dry conditions.' WHERE scientific_name = 'Astilbe × arendsii';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; very tough and long-flowering.' WHERE scientific_name = 'Rudbeckia fulgida';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; slugs may nibble young growth but damage is minor.' WHERE scientific_name = 'Lamprocapnos spectabilis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; slugs may eat young leaves in wet springs.' WHERE scientific_name = 'Brunnera macrophylla';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; self-seeds freely with no pest issues.' WHERE scientific_name = 'Eschscholzia californica';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Slugs and snails can be troublesome; otherwise fairly robust.' WHERE scientific_name = 'Campanula persicifolia';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a robust ornamental grass.' WHERE scientific_name = 'Miscanthus sinensis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; aphids may cluster on new growth in spring.' WHERE scientific_name = 'Lonicera periclymenum';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Aphids, black spot, rust, and sawfly are all common; roses need regular attention.' WHERE scientific_name = 'Rosa multiflora';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Columbine sawfly and aphids can defoliate; leaf miner creates white trails.' WHERE scientific_name = 'Aquilegia vulgaris';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally a tough, long-flowering perennial.' WHERE scientific_name = 'Coreopsis grandiflora';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can build up; earwigs may damage blooms.' WHERE scientific_name = 'Cosmos bipinnatus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; a tough and spreading ground cover.' WHERE scientific_name = 'Lysimachia nummularia';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Earwigs, aphids, slugs, and capsid bugs all target dahlias; tubers attract vine weevil.' WHERE scientific_name = 'Dahlia × pinnata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; tough and almost indestructible once established.' WHERE scientific_name = 'Hemerocallis fulva';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs, snails, and powdery mildew are serious problems; very attractive to pests.' WHERE scientific_name = 'Delphinium × cultorum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; tough native wildflower that wildlife tends to avoid eating.' WHERE scientific_name = 'Echinacea purpurea';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; slugs may eat seedlings but established plants are tough.' WHERE scientific_name = 'Digitalis purpurea';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; tough and drought-tolerant.' WHERE scientific_name = 'Gaillardia × grandiflora';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Virtually pest-free; an airy, low-maintenance perennial.' WHERE scientific_name = 'Oenothera lindheimeri';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; vine weevil may affect potted plants.' WHERE scientific_name = 'Geranium sanguineum';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Spiny and tough; virtually pest-free.' WHERE scientific_name = 'Echinops ritro';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough and reliable perennial.' WHERE scientific_name = 'Heliopsis helianthoides';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; tough leathery leaves deter browsers and insects.' WHERE scientific_name = 'Helleborus orientalis';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Vine weevil can damage roots especially in pots; generally pest-free in the ground.' WHERE scientific_name = 'Heuchera × hybrida';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Hollyhock rust is almost inevitable; aphids and flea beetles also common.' WHERE scientific_name = 'Alcea rosea';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Slugs and snails devour hostas relentlessly; vine weevil also attacks roots.' WHERE scientific_name = 'Hosta spp.';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Iris borer (in N. America) and iris sawfly can cause damage; leaf spot in wet weather.' WHERE scientific_name = 'Iris germanica';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters almost all pests; rosemary beetle occasionally in mild areas.' WHERE scientific_name = 'Lavandula angustifolia';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Lupin aphid is a serious specific pest; slugs also eat young growth.' WHERE scientific_name = 'Lupinus polyphyllus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Aromatic foliage deters many pests; useful companion plant.' WHERE scientific_name = 'Tagetes patula';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a tough mat-forming ground cover.' WHERE scientific_name = 'Mazus reptans';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a robust ornamental grass.' WHERE scientific_name = 'Miscanthus × giganteus';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blackfly (black bean aphid) and caterpillars are very common; often used as a trap crop.' WHERE scientific_name = 'Tropaeolum majus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; generally tough and trouble-free.' WHERE scientific_name = 'Penstemon × hybrida';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Peony wilt (botrytis) can cause buds to brown; ants on buds are harmless.' WHERE scientific_name = 'Paeonia lactiflora';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and tobacco mosaic virus can be problematic; slugs eat seedlings.' WHERE scientific_name = 'Petunia × hybrida';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Powdery mildew is almost inevitable; eelworm can be a serious problem.' WHERE scientific_name = 'Phlox paniculata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; self-seeds freely and is generally trouble-free.' WHERE scientific_name = 'Papaver rhoeas';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Vine weevil and slugs can be problematic; generally tougher outdoors than in pots.' WHERE scientific_name = 'Primula vulgaris';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; slugs may eat young leaves in wet conditions.' WHERE scientific_name = 'Pulmonaria officinalis';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Aphids, black spot, rust, sawfly, and thrips all target roses; regular monitoring essential.' WHERE scientific_name = 'Rosa × hybrida';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can build up; powdery mildew in dry weather. Generally short-lived.' WHERE scientific_name = 'Rudbeckia hirta';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; aromatic foliage helps deter insects.' WHERE scientific_name = 'Salvia nemorosa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; generally tough and trouble-free.' WHERE scientific_name = 'Scabiosa atropurpurea';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; succulent leaves and tough constitution deter most pests.' WHERE scientific_name = 'Sedum spectabile';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; aphids occasionally but generally robust.' WHERE scientific_name = 'Leucanthemum × superbum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Rust and aphids can be problems; antirrhinum rust causes orange pustules on leaves.' WHERE scientific_name = 'Antirrhinum majus';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; woolly silver foliage deters browsers and insects.' WHERE scientific_name = 'Cerastium tomentosum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Slugs eat seedlings; birds and squirrels take seeds from mature heads.' WHERE slug = 'sunflower';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Slugs eat seedlings; birds and squirrels take seeds from mature heads.' WHERE slug = 'sunflower-biomass';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Aphids, slugs, thrips, and pea moth can all be problematic; birds peck flowers.' WHERE scientific_name = 'Lathyrus odoratus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; slugs may eat very young growth but established plants are robust.' WHERE scientific_name = 'Trillium grandiflorum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally a tough, self-seeding perennial.' WHERE scientific_name = 'Verbena bonariensis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; a tough and low-maintenance perennial.' WHERE scientific_name = 'Veronica spicata';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; aromatic foliage deters most insects.' WHERE scientific_name = 'Achillea millefolium';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids, powdery mildew, and bacterial leaf spot can occur; generally manageable.' WHERE scientific_name = 'Zinnia elegans';

-- ============================================================
-- SHRUBS
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; tough and spiny native hedging plant.' WHERE scientific_name = 'Prunus spinosa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a tough native hedging shrub.' WHERE scientific_name = 'Cornus sanguinea';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a tough and ornamental shrub.' WHERE scientific_name = 'Cornus alba';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; scale insects occasionally in sheltered spots.' WHERE scientific_name = 'Escallonia × exoniensis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Spiny and tough; virtually nothing eats it.' WHERE scientific_name = 'Ulex europaeus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free in mild coastal areas; can suffer leaf spot in damp conditions.' WHERE scientific_name = 'Griselinia littoralis';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Nut weevil and squirrels target nuts; big bud mite occasionally.' WHERE slug = 'hazel-hedge';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a tough nitrogen-fixing shrub.' WHERE scientific_name = 'Amorpha fruticosa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and leaf spot can be problems; generally manageable with good airflow.' WHERE slug = 'privet-common';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids, thrips, and leaf spot can occur; honey fungus is a risk.' WHERE scientific_name = 'Ligustrum ovalifolium';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Sawfly larvae and rose aphid can be troublesome; generally tougher than hybrid roses.' WHERE scientific_name = 'Rosa rugosa';

-- ============================================================
-- TREES
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Less susceptible to ash dieback than common ash but not immune; generally robust.' WHERE scientific_name = 'Fraxinus ornus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; beech bark disease and woolly beech aphid occasionally.' WHERE slug = 'beech-hedge-copper';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; beech bark disease and woolly beech aphid occasionally.' WHERE slug = 'beech-hedge-green';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Dutch elm disease has devastated this species; elm bark beetle is the vector.' WHERE scientific_name = 'Ulmus procera';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; an ancient species with remarkable disease resistance.' WHERE scientific_name = 'Ginkgo biloba';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; webworm occasionally but rarely serious.' WHERE slug = 'honey-locust';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough native hedging and specimen tree.' WHERE slug = 'hornbeam-hedge';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can produce heavy honeydew; lime nail gall mite is cosmetic only.' WHERE scientific_name = 'Tilia platyphyllos';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can produce heavy honeydew; lime nail gall mite is cosmetic only.' WHERE slug = 'linden-smallleaf';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; generally a tough and adaptable maple.' WHERE scientific_name = 'Acer × freemanii';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Asian longhorned beetle and verticillium wilt are potential threats; tar spot is cosmetic.' WHERE scientific_name = 'Acer saccharum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pecan weevil and hickory shuckworm can damage nuts; scab in humid climates.' WHERE scientific_name = 'Carya illinoinensis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; anthracnose occasionally but generally very tough.' WHERE slug = 'plane-london';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Poplar rust, bacterial canker, and poplar beetles can be problematic.' WHERE scientific_name = 'Populus × canadensis';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Chestnut blight is devastating where present; ink disease and weevils also a concern.' WHERE slug = 'sweet-chestnut';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally tough in mild climates.' WHERE scientific_name = 'Acacia baileyana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally tough in mild climates.' WHERE slug = 'tree-acacia-dealbata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; psyllids may occasionally appear.' WHERE scientific_name = 'Acacia longifolia';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; mimosa webworm can defoliate in some regions.' WHERE slug = 'tree-albizia-julibrissin';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Alder leaf beetle and phytophthora can be issues; generally a tough pioneer species.' WHERE slug = 'tree-alder-black';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Alder leaf beetle and phytophthora are the main risks; generally tough and vigorous.' WHERE slug = 'tree-alder-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; a tough pioneer species in upland areas.' WHERE scientific_name = 'Alnus viridis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; phytophthora root disease is the main risk in wet soils.' WHERE scientific_name = 'Alnus incana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; alder flea beetle occasionally but damage is minor.' WHERE scientific_name = 'Alnus rubra';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Bronze birch borer can be serious in stressed trees; birch leaf miner common.' WHERE scientific_name = 'Betula alleghaniensis';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; a tough and adaptable small maple.' WHERE scientific_name = 'Acer ginnala';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Bagworm and leaf miner can be issues; generally fairly robust.' WHERE scientific_name = 'Thuja occidentalis';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Ash dieback (Hymenoscyphus fraxineus) is devastating; emerald ash borer also a major threat.' WHERE scientific_name = 'Fraxinus excelsior';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; a fast-growing, wind-resistant native tree.' WHERE scientific_name = 'Populus tremula';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; beech bark disease and woolly beech aphid occasionally.' WHERE slug = 'tree-beech';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally tough and long-lived.' WHERE scientific_name = 'Acacia melanoxylon';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few serious pests; locust borer and leaf miner occasionally but tree is resilient.' WHERE scientific_name = 'Robinia pseudoacacia';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; spruce aphid may appear in mild winters.' WHERE scientific_name = 'Picea mariana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; willow beetle and aphids occasionally.' WHERE scientific_name = 'Salix nigra';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Spruce aphid and red spider mite can cause needle drop; Cooley spruce gall adelgid.' WHERE scientific_name = 'Picea pungens';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a very tough nitrogen-fixing tree.' WHERE scientific_name = 'Caragana arborescens';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; generally a tough and long-lived conifer.' WHERE scientific_name = 'Cedrus atlantica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; a majestic and generally healthy conifer.' WHERE scientific_name = 'Cedrus libani';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; beech bark disease occasionally.' WHERE slug = 'tree-copper-beech';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; processionary moth caterpillars can be an issue in some areas.' WHERE scientific_name = 'Pinus nigra subsp. laricio';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Apple scab, fireblight, and aphids are common; similar pest profile to apple.' WHERE scientific_name = 'Malus × floribunda';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; Douglas fir adelgid may cause galls but damage is usually minor.' WHERE scientific_name = 'Pseudotsuga menziesii';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Bronze birch borer in stressed trees; birch leaf miner and aphids common.' WHERE scientific_name = 'Betula pubescens';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; a tough nitrogen-fixing evergreen.' WHERE scientific_name = 'Elaeagnus × ebbingei';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; a tough nitrogen-fixing shrub-tree.' WHERE scientific_name = 'Elaeagnus commutata';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Dutch elm disease is a serious threat; elm bark beetle is the vector.' WHERE scientific_name = 'Ulmus pumila';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Dutch elm disease has been catastrophic for this species; elm bark beetle spreads the fungus.' WHERE scientific_name = 'Ulmus glabra';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; eucalyptus gall wasp and psyllids occasionally in mild areas.' WHERE scientific_name = 'Eucalyptus gunnii';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; aromatic oils provide natural resistance.' WHERE scientific_name = 'Eucalyptus niphophila';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; adelgids occasionally but generally healthy.' WHERE scientific_name = 'Abies alba';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pests; tar spot on leaves is cosmetic. A tough native hedging tree.' WHERE scientific_name = 'Acer campestre';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; generally a tough and trouble-free ornamental tree.' WHERE scientific_name = 'Laburnum × watereri';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally a robust and trouble-free ornamental.' WHERE scientific_name = 'Koelreuteria paniculata';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; an extremely tough and adaptable tree.' WHERE slug = 'tree-hackberry-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Hawthorn leaf miner and midland hawthorn aphid occur but damage is rarely serious.' WHERE slug = 'tree-hawthorn-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Similar pest profile to common hawthorn; leaf miner and aphids occasionally.' WHERE slug = 'tree-hawthorn-crimson';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Hawthorn leaf miner and aphids occur but damage is rarely serious.' WHERE slug = 'tree-hawthorn-midland';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Nut weevil and squirrels are the main problems; big bud mite occasionally.' WHERE slug = 'tree-hazel-harry-lauder';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Nut weevil and squirrels target nuts; big bud mite occasionally.' WHERE slug = 'tree-hazel-treeform';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Holly leaf miner and leaf blight are cosmetic issues; generally very tough.' WHERE scientific_name = 'Ilex aquifolium';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; webworm occasionally but rarely serious.' WHERE slug = 'tree-honey-locust';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a tough, low-maintenance fruiting shrub.' WHERE slug = 'tree-honeyberry-treeform';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough native tree ideal for hedging.' WHERE slug = 'tree-hornbeam';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids, scale insects, and verticillium wilt can affect it; coral spot on dead wood.' WHERE scientific_name = 'Acer palmatum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; a tough and elegant specimen tree.' WHERE scientific_name = 'Zelkova serrata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; birds take fruit but the tree is trouble-free.' WHERE scientific_name = 'Amelanchier lamarckii';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters most pests; juniper scale very rarely an issue.' WHERE slug = 'tree-juniper-common';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; a beautiful and generally trouble-free specimen tree.' WHERE scientific_name = 'Cercidiphyllum japonicum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Larch adelgid and larch casebearer may cause some needle loss; generally robust.' WHERE scientific_name = 'Larix decidua';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Phytophthora root rot has devastated many specimens; cypress aphid also a threat.' WHERE scientific_name = 'Chamaecyparis lawsoniana';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Lilac borer and powdery mildew are the main concerns; bacterial blight occasionally.' WHERE scientific_name = 'Syringa vulgaris';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids can produce heavy honeydew; lime nail gall mite is cosmetic only.' WHERE slug = 'tree-lime-small-leaved';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; mountain pine beetle not a major issue in UK/Ireland.' WHERE scientific_name = 'Pinus contorta';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; anthracnose occasionally but generally very tough.' WHERE slug = 'tree-london-plane';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; scale insects very occasionally.' WHERE scientific_name = 'Magnolia grandiflora';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally a trouble-free ornamental tree.' WHERE scientific_name = 'Magnolia × soulangeana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally a trouble-free small tree.' WHERE scientific_name = 'Magnolia stellata';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; extremely tough and adapted to harsh conditions.' WHERE scientific_name = 'Prosopis glandulosa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; generally tough in mild climates.' WHERE slug = 'tree-mimosa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pine processionary moth and red band needle blight can cause defoliation.' WHERE scientific_name = 'Pinus radiata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; birds take berries but the tree is resilient.' WHERE slug = 'tree-mountain-ash-dwarf';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Horse chestnut leaf miner is not a threat, but tar spot and aphids are common.' WHERE scientific_name = 'Acer platanoides';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Spruce aphid and red spider mite can cause needle drop in mild winters.' WHERE scientific_name = 'Picea abies';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; generally a very tough and long-lived native oak.' WHERE slug = 'tree-oak-burr';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Oak processionary moth, powdery mildew, and acute oak decline are all concerns.' WHERE scientific_name = 'Quercus robur';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Fewer pest problems than English oak; generally a robust and adaptable tree.' WHERE scientific_name = 'Quercus rubra';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a very tough and long-lived tree.' WHERE scientific_name = 'Styphnolobium japonicum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; an attractive small ornamental maple.' WHERE scientific_name = 'Acer griseum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; pine processionary moth is the main risk in warmer areas.' WHERE scientific_name = 'Pinus ponderosa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Poplar rust, bacterial canker, and poplar beetle can be problematic.' WHERE scientific_name = 'Populus nigra';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Poplar rust and aphids can be troublesome; poplar beetle occasionally.' WHERE scientific_name = 'Populus alba';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Asian longhorned beetle is a potential threat; verticillium wilt and tar spot common.' WHERE scientific_name = 'Acer rubrum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; a tough and attractive native tree.' WHERE scientific_name = 'Cercis canadensis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; thick bark and resinous wood deter all but the most determined pests.' WHERE scientific_name = 'Sequoiadendron giganteum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; birds take berries but the tree is resilient.' WHERE slug = 'tree-rowan-mountain-ash';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; pine processionary moth is the main concern in some regions.' WHERE scientific_name = 'Pinus sylvestris';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; a living fossil with exceptional resilience.' WHERE scientific_name = 'Metasequoia glyptostroboides';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; a tough and underrated native fruit tree.' WHERE scientific_name = 'Sorbus domestica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; birds take fruit but the tree is trouble-free.' WHERE slug = 'tree-serviceberry-treeform';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; extremely tough and adapted to poor soils.' WHERE scientific_name = 'Casuarina equisetifolia';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; mimosa webworm can defoliate in some areas.' WHERE slug = 'tree-silk-tree';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Bronze birch borer in stressed trees; birch leaf miner and aphids are common.' WHERE scientific_name = 'Betula pendula';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Fewer aphid problems than other limes; generally a robust specimen tree.' WHERE scientific_name = 'Tilia tomentosa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Verticillium wilt and tar spot are possible; generally fairly robust but can be stressed.' WHERE scientific_name = 'Acer saccharinum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough and attractive ornamental shrub-tree.' WHERE scientific_name = 'Cotinus coggygria';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Generally pest-free; birds take fruit but the tree is trouble-free.' WHERE scientific_name = 'Amelanchier × grandiflora';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Chestnut blight is devastating where present; ink disease and weevils also a concern.' WHERE slug = 'tree-sweet-chestnut';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; a tough ornamental tree.' WHERE scientific_name = 'Liquidambar styraciflua';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Sycamore aphid can produce copious honeydew; tar spot and sooty bark disease occur.' WHERE scientific_name = 'Acer pseudoplatanus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; a tough ornamental maple.' WHERE scientific_name = 'Acer pictum';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; extremely tough and salt-tolerant.' WHERE scientific_name = 'Tamarix ramosissima';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Virtually pest-free; toxic foliage deters browsers.' WHERE scientific_name = 'Dermatophyllum secundiflorum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; tulip tree scale and aphids occasionally.' WHERE slug = 'tree-tulip-poplar';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Willow aphid, sawfly, and rust can be troublesome; watermark disease also a risk.' WHERE scientific_name = 'Salix × sepulcralis';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Aromatic foliage deters most pests; virtually trouble-free once established.' WHERE scientific_name = 'Thuja plicata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues; scale insects very rarely. Tough and long-lived native.' WHERE scientific_name = 'Taxus baccata';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; tulip tree scale and aphids occasionally.' WHERE slug = 'tulip-tree';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few serious pests; squirrels may take nuts before you do.' WHERE slug = 'walnut-black';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Walnut blotch and walnut aphid are occasional problems; squirrels take nuts.' WHERE slug = 'walnut-english';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Willow beetle, aphids, and rust can all be issues; watermark disease in wet soils.' WHERE scientific_name = 'Salix viminalis';

-- ============================================================
-- VEGETABLES
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; flea beetles occasionally nibble leaves.' WHERE scientific_name = 'Amaranthus tricolor';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Blackfly can colonise stems; slugs eat young plants. Generally manageable.' WHERE scientific_name = 'Cynara scolymus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Asparagus beetle is the main pest; otherwise fairly trouble-free once established.' WHERE scientific_name = 'Asparagus officinalis';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Red spider mite, whitefly, and aphids under glass; flea beetle outdoors. Needs vigilance.' WHERE scientific_name = 'Solanum melongena';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Blackfly, slugs, and bean seed fly can be problematic; generally manageable.' WHERE slug = 'bean';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Leaf miner creates pale tunnels; generally fairly robust otherwise.' WHERE scientific_name = 'Beta vulgaris' AND slug = 'beetroot';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a tough and underrated root vegetable.' WHERE scientific_name = 'Scorzonera hispanica';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blackfly is almost inevitable; chocolate spot fungus in damp conditions.' WHERE slug = 'broad-bean';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Cabbage white caterpillars, aphids, and pigeons are major threats; netting essential.' WHERE slug = 'broccoli';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Cabbage white caterpillars, mealy cabbage aphid, and pigeons all target them; whitefly too.' WHERE scientific_name = 'Brassica oleracea var. gemmifera';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests bother it; robust and vigorous root vegetable.' WHERE slug = 'burdock-root';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Cabbage white caterpillars are the main threat; also mealy aphid, pigeons, and clubroot.' WHERE slug = 'cabbage';
UPDATE plant_species SET pest_resilience_score = 1, pest_resilience_note = 'Cabbage white caterpillars, mealy aphid, and clubroot; netting is essential.' WHERE slug = 'cabbage-green';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Same pests as green cabbage; slightly more resistant but still needs protection.' WHERE scientific_name = 'Brassica oleracea var. capitata f. rubra';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Crinkled leaves harbour aphids; cabbage white caterpillars and whitefly are threats.' WHERE scientific_name = 'Brassica oleracea var. sabauda';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Blackfly can colonise stems; slugs eat young plants. Spiny stems help deter browsers.' WHERE scientific_name = 'Cynara cardunculus';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Carrot fly is a major pest; use fleece barriers or companion plant with alliums.' WHERE scientific_name = 'Daucus carota subsp. sativus';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Whitefly and mealybug under cover; generally robust outdoors in tropical climates.' WHERE scientific_name = 'Manihot esculenta';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Cabbage white caterpillars, mealy aphid, and clubroot all cause problems; needs netting.' WHERE scientific_name = 'Brassica oleracea var. botrytis' AND slug = 'cauliflower';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Celery leaf miner and slugs are the main pests; leaf spot in wet weather.' WHERE scientific_name = 'Apium graveolens var. rapaceum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Celery leaf miner and slugs are the main pests; leaf spot in wet weather.' WHERE scientific_name = 'Apium graveolens var. dulce';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; vigorous grower that outpaces most pests.' WHERE scientific_name = 'Sechium edule';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pod borer and leaf miner can be issues; generally manageable.' WHERE scientific_name = 'Cicer arietinum';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Flea beetle, slugs, and cabbage caterpillars can be serious; bolts quickly in stress.' WHERE scientific_name = 'Brassica rapa subsp. pekinensis';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs love courgettes; powdery mildew is almost inevitable later in the season.' WHERE scientific_name = 'Cucurbita pepo' AND slug = 'courgette';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a tough and heat-tolerant legume.' WHERE scientific_name = 'Vigna unguiculata subsp. unguiculata';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Red spider mite, whitefly, and powdery mildew under glass; slugs outdoors.' WHERE slug = 'cucumber';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Same pests as salad cucumber; powdery mildew and red spider mite under glass.' WHERE slug = 'cucumber-pickling';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Flea beetle can riddle leaves; generally robust once past seedling stage.' WHERE scientific_name = 'Raphanus sativus var. longipinnatus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; very few problems.' WHERE scientific_name = 'Allium ampeloprasum' AND slug = 'elephant-garlic';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and slugs can be problematic; generally fairly robust.' WHERE scientific_name = 'Cichorium endivia' AND slug = 'endive';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and slugs can be problematic; generally fairly robust.' WHERE scientific_name = 'Cichorium endivia var. latifolium';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blackfly and chocolate spot are almost inevitable; needs early sowing and pinching out tips.' WHERE slug = 'fava-bean';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids may cluster on flower heads; generally robust.' WHERE scientific_name = 'Foeniculum vulgare var. azoricum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a tough green with aromatic properties.' WHERE scientific_name = 'Trigonella foenum-graecum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Blackfly, slugs, and bean seed fly can be problematic; generally manageable.' WHERE slug = 'french-bean';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Allium chemistry provides excellent pest resistance; virtually trouble-free.' WHERE scientific_name = 'Allium sativum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium family chemistry deters most pests; very few problems.' WHERE scientific_name = 'Allium tuberosum';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; needs warmth and shelter but pest problems are rare.' WHERE scientific_name = 'Zingiber officinale';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Flea beetles may damage leaves; generally fairly trouble-free.' WHERE scientific_name = 'Physalis pruinosa';
UPDATE plant_species SET pest_resilience_score = 5, pest_resilience_note = 'Pungent roots deter virtually all pests; flea beetles very rarely.' WHERE scientific_name = 'Armoracia rusticana';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; slugs may eat tubers in wet soil but damage is minor.' WHERE scientific_name = 'Helianthus tuberosus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest issues in temperate climates; generally robust.' WHERE scientific_name = 'Pachyrhizus erosus';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Cabbage white caterpillars, mealy aphid, and whitefly are common; netting helps.' WHERE slug = 'kale-curly';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Same pests as curly kale; caterpillars and whitefly are the main threats.' WHERE scientific_name = 'Brassica oleracea var. palmifolia';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Cabbage white caterpillars and flea beetle are the main threats; less prone than cabbage.' WHERE scientific_name = 'Brassica oleracea Gongylodes Group';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Allium leaf miner and leek moth are increasing threats; rust also common.' WHERE scientific_name = 'Allium ampeloprasum var. porrum';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs, aphids, and lettuce root aphid are common; downy mildew in damp weather.' WHERE slug = 'lettuce';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Very attractive to slugs; lettuce root aphid and downy mildew also a risk.' WHERE slug = 'lettuce-butterhead';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs and aphids love it; tip burn in hot weather adds stress.' WHERE slug = 'lettuce-iceberg';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Less slug-prone than butterhead types; aphids still a risk.' WHERE slug = 'lettuce-looseleaf';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'More slug-resistant than soft lettuces; aphids and downy mildew still possible.' WHERE slug = 'lettuce-romaine';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Bean seed fly and aphids can be problems; generally manageable.' WHERE scientific_name = 'Phaseolus lunatus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a vigorous tropical climber.' WHERE scientific_name = 'Basella alba';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Powdery mildew and aphids possible; generally fairly trouble-free under glass.' WHERE scientific_name = 'Cucumis melo';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Flea beetle can riddle leaves; generally robust once past the seedling stage.' WHERE scientific_name = 'Brassica rapa var. nipposinica';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; few problems.' WHERE slug = 'multiplier-onion';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Flea beetle and caterpillars can be issues; fast-growing so often harvested before damage.' WHERE scientific_name = 'Brassica juncea';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and flea beetles can be problematic; generally manageable with good growing conditions.' WHERE scientific_name = 'Abelmoschus esculentus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; onion fly and allium leaf miner are the main risks.' WHERE slug = 'onion';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; onion fly and allium leaf miner are the main risks.' WHERE slug = 'onion-bulb';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Flea beetle, cabbage caterpillars, and slugs all target it; needs protection.' WHERE scientific_name = 'Brassica rapa subsp. chinensis';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Carrot fly can tunnel roots; canker is also a risk. Use resistant varieties.' WHERE scientific_name = 'Pastinaca sativa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pea moth, pea aphid, and birds are the main threats; net early sowings.' WHERE slug = 'pea';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pea moth, pea aphid, and birds targeting seedlings and pods.' WHERE slug = 'peas-garden';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pea moth and pea aphid can be troublesome; generally productive.' WHERE slug = 'peas-snap';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Pea moth and pea aphid; flat pods make moth damage less of an issue.' WHERE slug = 'peas-snow';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids, red spider mite under glass, and blossom end rot (cultural issue).' WHERE slug = 'pepper';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and red spider mite under glass; capsaicin deters some pests.' WHERE slug = 'pepper-chilli';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Capsaicin strongly deters most pests; aphids under glass occasionally.' WHERE scientific_name = 'Capsicum chinense';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and red spider mite under glass; generally similar to chilli peppers.' WHERE slug = 'pepper-sweet';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blight is the main risk in wet summers; also slug damage and wireworm.' WHERE scientific_name = 'Solanum tuberosum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Powdery mildew is common; squash vine borer in some regions. Slugs eat young plants.' WHERE scientific_name = 'Cucurbita maxima';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a tough and easy-to-grow edible weed.' WHERE scientific_name = 'Portulaca oleracea';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and slugs occasionally; generally fairly robust.' WHERE scientific_name = 'Cichorium intybus var. foliosum';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Flea beetle can riddle leaves with tiny holes; quick growing so often harvested first.' WHERE slug = 'radish';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium family chemistry deters most pests; very few problems.' WHERE scientific_name = 'Allium chinense';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests once established; crown rot if soil is waterlogged.' WHERE scientific_name = 'Rheum × hybridum';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Flea beetle can devastate seedlings; slugs also a problem.' WHERE scientific_name = 'Eruca vesicaria subsp. sativa';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Cabbage white caterpillars and mealy aphid; same pest profile as broccoli.' WHERE slug = 'romanesco';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Blackfly, slugs, and halo blight can be problematic; pinch out tips to deter blackfly.' WHERE slug = 'runner-bean';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a robust and underrated root vegetable.' WHERE scientific_name = 'Tragopogon porrifolius';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Blackfly, slugs, and halo blight can be problematic; pinch out tips to deter blackfly.' WHERE slug = 'scarlet-runner-bean';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; few problems.' WHERE slug = 'shallot';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pests; slugs may nibble young leaves but it recovers quickly.' WHERE slug = 'sorrel';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and bean beetles can be issues; generally manageable.' WHERE scientific_name = 'Glycine max';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs are the main enemy; downy mildew and leaf spot in wet weather.' WHERE scientific_name = 'Spinacia oleracea';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Allium chemistry deters most pests; onion thrips occasionally.' WHERE scientific_name = 'Allium fistulosum';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Cabbage white caterpillars, mealy aphid, and whitefly; same pest profile as broccoli.' WHERE slug = 'sprouting-broccoli';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs and powdery mildew; squash vine borer in some regions.' WHERE slug = 'squash-pattypan';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Powdery mildew is common later in season; generally robust.' WHERE slug = 'squash-spaghetti';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Powdery mildew and slugs; squash vine borer in some regions.' WHERE scientific_name = 'Cucurbita moschata';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Slugs and powdery mildew are very common; harvest regularly.' WHERE slug = 'squash-yellow';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Flea beetle, cabbage caterpillars, and clubroot; same brassica pest profile.' WHERE scientific_name = 'Brassica napus subsp. rapifera';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Whitefly can build up; slugs eat tubers. Generally fewer pest issues than potato.' WHERE scientific_name = 'Ipomoea batatas';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Corn earworm and slugs at seedling stage; birds may take kernels.' WHERE scientific_name = 'Zea mays convar. saccharata';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Leaf miner and slugs; generally fairly robust.' WHERE slug = 'swiss-chard';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and spider mites under cover; generally few problems outdoors.' WHERE scientific_name = 'Colocasia esculenta';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Flea beetle can devastate seedlings; cabbage caterpillars and slugs also common.' WHERE scientific_name = 'Brassica rapa subsp. narinosa';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Generally fairly pest-free; Colorado beetle is a statutory pest (not established in UK).' WHERE scientific_name = 'Physalis philadelphica';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blight is devastating in wet summers; also whitefly, aphids, and red spider mite under glass.' WHERE slug = 'tomato';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blight is the main risk outdoors; splitting fruit attracts wasps. Same pest profile as tomato.' WHERE slug = 'tomato-cherry';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Blight in wet summers; whitefly under glass. Determinate habit can help avoid late blight.' WHERE slug = 'tomato-plum';
UPDATE plant_species SET pest_resilience_score = 2, pest_resilience_note = 'Flea beetle, cabbage caterpillars, and clubroot; same brassica pest profile as swede.' WHERE scientific_name = 'Brassica rapa subsp. rapa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few pest problems; whitefly occasionally but generally trouble-free.' WHERE scientific_name = 'Nasturtium officinale';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Aphids and red spider mite under glass; generally fewer pest issues outdoors.' WHERE scientific_name = 'Citrullus lanatus';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; slugs may eat tubers in very wet conditions.' WHERE scientific_name = 'Smallanthus sonchifolius';

-- ============================================================
-- VINES
-- ============================================================

UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a vigorous and trouble-free climber.' WHERE scientific_name = 'Akebia quinata';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Powdery mildew and grey mould are the main threats; birds and wasps take fruit.' WHERE scientific_name = 'Vitis vinifera';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Hop aphid (damson-hop aphid) can build up; downy mildew in wet seasons.' WHERE scientific_name = 'Humulus lupulus';
UPDATE plant_species SET pest_resilience_score = 3, pest_resilience_note = 'Scale insects and passion vine hopper occasionally; generally fairly robust.' WHERE scientific_name = 'Actinidia deliciosa';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Few significant pests; cats may nibble young plants due to actinidine.' WHERE slug = 'kiwi-hardy';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest problems; a tough ornamental climber.' WHERE scientific_name = 'Passiflora caerulea';
UPDATE plant_species SET pest_resilience_score = 4, pest_resilience_note = 'Very few pest issues; a tough and vigorous vine.' WHERE scientific_name = 'Schisandra chinensis';

COMMIT;
