export const ACTIVITY_KEYWORDS: Record<string, Record<string, string[]>> = {
    /* ----------------------------- OUTDOOR: WATER & FISHING ----------------------------- */
    fishing: {
      en: ["fishing spot","angling","fishing area","tackle shop"],
      es: ["pesca","lugar de pesca","zona de pesca","tienda de pesca"],
      fr: ["pêche","lieu de pêche","zone de pêche","magasin de pêche"],
      de: ["Angeln","Angelplatz","Angelgebiet","Angelladen"],
      it: ["pesca","posto di pesca","zona di pesca","negozio di pesca"],
      pt: ["pesca","local de pesca","área de pesca","loja de pesca"],
      zh: ["钓鱼","钓鱼地点","钓鱼区","渔具店"],
      ja: ["釣り","釣り場","釣りエリア","釣具店"],
    },
    fly_fishing_freshwater: {
      en: ["fly fishing","trout river","trout stream","fly fishing spot"],
      es: ["pesca con mosca","río truchero","arroyo de truchas","zona de pesca con mosca"],
      fr: ["pêche à la mouche","rivière à truites","ruisseau à truites","spot de pêche à la mouche"],
      de: ["Fliegenfischen","Forellenfluss","Forellenbach","Fliegenfischergebiet"],
      it: ["pesca a mosca","fiume di trote","torrente di trote","zona di pesca a mosca"],
      pt: ["pesca com mosca","rio de trutas","riacho de trutas","local de pesca com mosca"],
      zh: ["飞蝇钓","鳟鱼河","鳟鱼溪流","飞蝇钓地点"],
      ja: ["フライフィッシング","マス川","マスの渓流","フライ釣り場"],
    },
    coarse_fishing: {
      en: ["coarse fishing","carp lake","fishing lake","coarse fishing spot"],
      es: ["pesca de ciprínidos","carpfishing","coto de pesca","embalse de carpa"],
      fr: ["pêche au coup","carpodrome","étang de pêche","carpe"],
      de: ["Weißfischangeln","Karpfenangeln","Angelsee","Karpfenteich"],
      it: ["pesca al colpo","pesca alla carpa","lago di pesca","carpodromo"],
      pt: ["pesca grossa","pesca de carpa","lago de pesca","carpodromo"],
      zh: ["粗放钓鱼","鲤鱼湖","钓鱼湖","钓鱼点"],
      ja: ["コースフィッシング","鯉釣り","釣り池","フィッシングエリア"],
    },
    sea_fishing_shore: {
      en: ["sea fishing","shore fishing","pier fishing","rock fishing"],
      es: ["pesca en el mar","pesca desde la orilla","pesca en el espigón","pesca en rocas"],
      fr: ["pêche en mer","pêche du bord","pêche sur la jetée","pêche sur rochers"],
      de: ["Meeresangeln","Brandungsangeln","Angeln am Pier","Felsenangeln"],
      it: ["pesca in mare","pesca da riva","pesca dal molo","pesca sugli scogli"],
      pt: ["pesca marítima","pesca de costa","pesca no cais","pesca nas rochas"],
      zh: ["海钓","岸边钓鱼","码头钓鱼","礁石钓鱼"],
      ja: ["海釣り","岸釣り","桟橋釣り","磯釣り"],
    },
    sea_fishing_boat: {
      en: ["boat fishing","deep sea fishing","fishing charter","offshore fishing"],
      es: ["pesca en barco","pesca de altura","charter de pesca","pesca en alta mar"],
      fr: ["pêche en bateau","pêche en haute mer","charter de pêche","pêche au large"],
      de: ["Bootsangeln","Hochseefischen","Angelcharter","Offshore-Angeln"],
      it: ["pesca in barca","pesca d’altura","charter di pesca","pesca al largo"],
      pt: ["pesca de barco","pesca em alto-mar","charter de pesca","pesca offshore"],
      zh: ["船钓","深海钓鱼","钓鱼包船","近海钓鱼"],
      ja: ["船釣り","沖釣り","釣りチャーター","オフショア釣り"],
    },
    ice_fishing: {
      en: ["ice fishing","frozen lake fishing","ice hole fishing"],
      es: ["pesca en hielo","pesca en lago helado","pesca en agujero de hielo"],
      fr: ["pêche sur glace","pêche en lac gelé","pêche dans un trou de glace"],
      de: ["Eisangeln","Angeln im zugefrorenen See","Eislochangeln"],
      it: ["pesca sul ghiaccio","pesca in lago ghiacciato","pesca nel foro di ghiaccio"],
      pt: ["pesca no gelo","pesca em lago congelado","pesca no buraco de gelo"],
      zh: ["冰钓","冰湖钓鱼","冰洞钓鱼"],
      ja: ["氷上釣り","氷結湖の釣り","氷穴釣り"],
    },
  
    kayaking: {
      en: ["kayak rental","kayaking","canoe hire","kayak club"],
      es: ["alquiler de kayak","piragüismo","club de piragüismo","kayak río"],
      fr: ["location de kayak","kayak","canoë","club de kayak"],
      de: ["Kajakverleih","Kajakfahren","Kanufahren","Kajakclub"],
      it: ["noleggio kayak","canoa","club di kayak"],
      pt: ["aluguer de caiaque","caiaque","canoagem","clube de caiaque"],
      zh: ["皮划艇租赁","皮划艇运动","独木舟","皮划艇俱乐部"],
      ja: ["カヤック レンタル","カヤック","カヌー","カヤッククラブ"],
    },
    sea_kayaking: {
      en: ["sea kayaking","sea kayak tour","coastal kayak","ocean kayaking"],
      es: ["kayak de mar","ruta en kayak","excursión en kayak de mar"],
      fr: ["kayak de mer","randonnée en kayak","sortie kayak en mer"],
      de: ["Seekajak","Seekajaktour","Meereskajak"],
      it: ["kayak da mare","escursione in kayak","tour in kayak marino"],
      pt: ["caiaque no mar","excursão de caiaque","passeio de caiaque no mar"],
      zh: ["海上皮划艇","海上皮划艇之旅","沿海皮划艇"],
      ja: ["シーカヤック","海のカヤックツアー","沿岸カヤック"],
    },
    canoeing: {
      en: ["canoeing","canoe rental","canoe club"],
      es: ["piragüismo","canoa","club de piragüismo"],
      fr: ["canoë","location de canoë","club de canoë"],
      de: ["Kanufahren","Kanuverleih","Kanuverein"],
      it: ["canoa","noleggio canoa","club di canoa"],
      pt: ["canoagem","aluguer de canoa","clube de canoa"],
      zh: ["独木舟","独木舟租赁","独木舟俱乐部"],
      ja: ["カヌー","カヌーレンタル","カヌークラブ"],
    },
    stand_up_paddleboarding: {
      en: ["SUP rental","paddle board","stand up paddle"],
      es: ["paddle surf","alquiler paddle surf","SUP"],
      fr: ["stand up paddle","location paddle","SUP"],
      de: ["SUP Verleih","Stand Up Paddle","SUP mieten"],
      it: ["SUP","noleggio SUP","stand up paddle"],
      pt: ["stand up paddle","aluguer de SUP","SUP"],
      zh: ["桨板","站立式桨板","SUP租赁"],
      ja: ["SUP","スタンドアップパドル","SUPレンタル"],
    },
    surfing: {
      en: ["surfing","surf school","surf rental","surf beach"],
      es: ["surf","escuela de surf","alquiler de surf","playa de surf"],
      fr: ["surf","école de surf","location surf","plage de surf"],
      de: ["Surfen","Surfschule","Surfverleih","Surfstrand"],
      it: ["surf","scuola di surf","noleggio surf","spiaggia da surf"],
      pt: ["surf","escola de surf","aluguer de surf","praia de surf"],
      zh: ["冲浪","冲浪学校","冲浪板租赁","冲浪海滩"],
      ja: ["サーフィン","サーフィンスクール","サーフボードレンタル","サーフビーチ"],
    },
    windsurfing: {
      en: ["windsurfing","windsurf school","windsurf rental"],
      es: ["windsurf","escuela de windsurf","alquiler windsurf"],
      fr: ["windsurf","école de planche à voile","location windsurf"],
      de: ["Windsurfen","Windsurfschule","Windsurfverleih"],
      it: ["windsurf","scuola di windsurf","noleggio windsurf"],
      pt: ["windsurf","escola de windsurf","aluguer windsurf"],
      zh: ["风帆冲浪","风帆学校","风帆租赁"],
      ja: ["ウィンドサーフィン","ウィンドサーフィンスクール","ウィンドサーフィンレンタル"],
    },
    kitesurfing: {
      en: ["kitesurfing","kitesurf school","kiteboarding","kite surf rental"],
      es: ["kitesurf","escuela de kitesurf","alquiler kitesurf"],
      fr: ["kitesurf","école de kitesurf","location kitesurf"],
      de: ["Kitesurfen","Kitesurfschule","Kiteboarding"],
      it: ["kitesurf","scuola di kitesurf","noleggio kitesurf"],
      pt: ["kitesurf","escola de kitesurf","aluguer kitesurf"],
      zh: ["风筝冲浪","风筝冲浪学校","风筝冲浪租赁"],
      ja: ["カイトサーフィン","カイトサーフィンスクール","カイトサーフィンレンタル"],
    },
    snorkeling: {
      en: ["snorkelling","snorkel rental","snorkel spot","mask fins"],
      es: ["snorkel","alquiler de snorkel","zona de snorkel"],
      fr: ["snorkeling","location de matériel de plongée","spot de snorkeling"],
      de: ["Schnorcheln","Schnorchelverleih","Schnorchelplatz"],
      it: ["snorkeling","noleggio snorkeling","punto snorkeling"],
      pt: ["snorkel","aluguer de snorkel","local de snorkel"],
      zh: ["浮潜","浮潜装备租赁","浮潜点"],
      ja: ["シュノーケリング","シュノーケルレンタル","シュノーケルスポット"],
    },
    scuba_diving: {
      en: ["scuba diving","dive centre","PADI","scuba rental"],
      es: ["buceo","centro de buceo","PADI","alquiler buceo"],
      fr: ["plongée sous-marine","centre de plongée","PADI"],
      de: ["Tauchen","Tauchzentrum","PADI"],
      it: ["immersioni subacquee","centro sub","PADI"],
      pt: ["mergulho","centro de mergulho","PADI"],
      zh: ["水肺潜水","潜水中心","PADI"],
      ja: ["スキューバダイビング","ダイブセンター","PADI"],
    },
    wild_swimming: {
      en: ["wild swimming","river swimming","lake swimming","swim spot"],
      es: ["baño en río","baño en lago","zona de baño","poza"],
      fr: ["bain sauvage","rivière baignade","lac baignade"],
      de: ["Wildschwimmen","Flussschwimmen","Seeschwimmen"],
      it: ["nuoto selvaggio","nuotare nel fiume","nuotare nel lago"],
      pt: ["natação selvagem","nadar no rio","nadar no lago"],
      zh: ["野泳","河里游泳","湖里游泳"],
      ja: ["野外水泳","川で泳ぐ","湖で泳ぐ"],
    },
    sailing: {
      en: ["sailing","sailing club","yacht club","marina"],
      es: ["vela","club náutico","puerto deportivo"],
      fr: ["voile","club de voile","port de plaisance"],
      de: ["Segeln","Segelclub","Yachthafen"],
      it: ["vela","club velico","porto turistico"],
      pt: ["vela","clube de vela","marina"],
      zh: ["帆船","帆船俱乐部","游艇码头"],
      ja: ["セーリング","ヨットクラブ","マリーナ"],
    },
    sailing_inland: {
      en: ["inland sailing","dinghy sailing","lake sailing","sailing club"],
      es: ["vela en lago","vela ligera","club de vela de interior"],
      fr: ["voile sur lac","dériveur","club de voile"],
      de: ["Binnensegeln","Jollensegeln","Segelclub"],
      it: ["vela sul lago","deriva","club velico"],
      pt: ["vela em lago","vela ligeira","clube de vela"],
      zh: ["内陆航行","小艇航行","湖上航行"],
      ja: ["湖でのセーリング","ディンギーセーリング","セーリングクラブ"],
    },
    jetskiing: {
      en: ["jetskiing","jet ski rental","personal watercraft"],
      es: ["moto de agua","alquiler moto de agua","jetski"],
      fr: ["jet ski","location jet ski"],
      de: ["Jetski","Jetski Verleih"],
      it: ["moto d’acqua","noleggio moto d’acqua"],
      pt: ["mota de água","aluguer de jet ski"],
      zh: ["摩托艇","摩托艇租赁"],
      ja: ["ジェットスキー","ジェットスキーレンタル"],
    },
  
    /* ----------------------------------- OUTDOOR: LAND ---------------------------------- */
    running: {
      en: ["running route","running track","jogging park","trail run"],
      es: ["circuito de running","pista de atletismo","parque para correr","ruta de trail"],
      fr: ["parcours de course","piste d’athlétisme","parc jogging","trail"],
      de: ["Laufstrecke","Laufbahn","Joggingpark","Trailrunning"],
      it: ["percorso running","pista di atletica","parco per correre","trail running"],
      pt: ["rota de corrida","pista de atletismo","parque para correr","trilha de corrida"],
      zh: ["跑步路线","田径跑道","慢跑公园","越野跑"],
      ja: ["ランニングコース","陸上トラック","ジョギング公園","トレイルラン"],
    },
    hiking: {
      en: ["hiking trail","trailhead","nature reserve","national park"],
      es: ["sendero de montaña","inicio de ruta","parque natural","parque nacional"],
      fr: ["sentier de randonnée","départ de sentier","réserve naturelle","parc national"],
      de: ["Wanderweg","Wanderstartpunkt","Naturschutzgebiet","Nationalpark"],
      it: ["sentiero escursionistico","punto di partenza sentiero","riserva naturale","parco nazionale"],
      pt: ["trilha de caminhada","início da trilha","reserva natural","parque nacional"],
      zh: ["徒步小径","登山口","自然保护区","国家公园"],
      ja: ["ハイキングコース","登山口","自然保護区","国立公園"],
    },
    mountain_biking: {
      en: ["mountain bike trail","mtb singletrack","bike park","downhill route"],
      es: ["ruta de bicicleta de montaña","singletrack MTB","bike park","descenso en bici"],
      fr: ["sentier VTT","singletrack VTT","bike park","descente VTT"],
      de: ["MTB-Strecke","Singletrail","Bikepark","Downhill-Strecke"],
      it: ["sentiero MTB","singletrack","bike park","discesa MTB"],
      pt: ["trilha de MTB","singletrack MTB","bike park","descida de bicicleta"],
      zh: ["山地车路线","单行道MTB","自行车公园","下坡骑行"],
      ja: ["マウンテンバイク トレイル","シングルトラックMTB","バイクパーク","ダウンヒルコース"],
    },
    cycling: {
      en: ["bike rental","cycle route","cycling cafe","bike path"],
      es: ["alquiler de bicicletas","ruta ciclista","cafetería ciclista","carril bici"],
      fr: ["location de vélos","itinéraire cyclable","café cycliste","piste cyclable"],
      de: ["Fahrradverleih","Radroute","Radlercafé","Radweg"],
      it: ["noleggio bici","percorso ciclabile","caffè ciclistico","pista ciclabile"],
      pt: ["aluguer de bicicletas","rota de ciclismo","café ciclista","ciclovia"],
      zh: ["自行车租赁","骑行路线","骑行咖啡馆","自行车道"],
      ja: ["自転車レンタル","サイクリングルート","サイクリストカフェ","自転車道"],
    },
    skateboarding: {
      en: ["skatepark","pump track","skate spot"],
      es: ["skatepark","pista de skate","pump track"],
      fr: ["skatepark","piste de skate","pump track"],
      de: ["Skatepark","Skatespot","Pumptrack"],
      it: ["skatepark","pista di skate","pump track"],
      pt: ["skatepark","pista de skate","pump track"],
      zh: ["滑板公园","滑板场","泵道"],
      ja: ["スケートパーク","スケートスポット","パンプトラック"],
    },
    rollerblading: {
      en: ["rollerblading path","inline skating route","skate park"],
      es: ["circuito de patinaje","ruta de patinaje","pista de patinaje"],
      fr: ["piste de roller","itinéraire roller","parc de roller"],
      de: ["Inline-Skating Strecke","Rollerbahn","Skatepark"],
      it: ["percorso pattinaggio","pista di rollerblade","parco pattinaggio"],
      pt: ["rota de patins","pista de patinagem","parque de roller"],
      zh: ["轮滑道","轮滑路线","轮滑公园"],
      ja: ["ローラーブレードコース","インラインスケートルート","ローラーパーク"],
    },
    dog_walking: {
      en: ["dog park","off leash area","dog friendly park"],
      es: ["parque canino","zona para perros","parque dog-friendly"],
      fr: ["parc à chiens","espace canin","parc pour chiens"],
      de: ["Hundepark","Hundewiese","Hundefreilauf"],
      it: ["parco per cani","area cani","zona cani"],
      pt: ["parque canino","zona para cães","área de cães"],
      zh: ["狗狗公园","狗狗活动区","宠物友好公园"],
      ja: ["ドッグパーク","犬の運動場","犬OK公園"],
    },
    foraging: {
      en: ["foraging area","wild herbs","wild berries","edible plants"],
      es: ["zona de recolección","hierbas silvestres","bayas silvestres","plantas comestibles"],
      fr: ["zone de cueillette","herbes sauvages","baies sauvages","plantes comestibles"],
      de: ["Sammelgebiet","Wildkräuter","Waldbeeren","essbare Pflanzen"],
      it: ["zona di raccolta","erbe selvatiche","bacche selvatiche","piante commestibili"],
      pt: ["zona de forragem","ervas silvestres","bagas silvestres","plantas comestíveis"],
      zh: ["采集区","野生香草","野生浆果","可食用植物"],
      ja: ["採取エリア","野草","野生ベリー","食用植物"],
    },
    mushroom_hunting: {
      en: ["mushroom foraging","wild mushrooms","foraging area"],
      es: ["recolección de setas","setas silvestres","zona de recolección"],
      fr: ["cueillette de champignons","champignons sauvages","zone de cueillette"],
      de: ["Pilzsammeln","Waldpilze","Sammelgebiet"],
      it: ["raccolta funghi","funghi selvatici","zona di raccolta"],
      pt: ["colheita de cogumelos","cogumelos silvestres","zona de colheita"],
      zh: ["采蘑菇","野生蘑菇","采集区"],
      ja: ["きのこ採り","野生きのこ","採取エリア"],
    },
    picnicking: {
      en: ["picnic area","park picnic","picnic spot"],
      es: ["área de picnic","parque para picnic","zona de picnic"],
      fr: ["aire de pique-nique","parc pique-nique","spot pique-nique"],
      de: ["Picknickplatz","Park Picknick","Picknickbereich"],
      it: ["area picnic","parco picnic","zona picnic"],
      pt: ["área de piquenique","parque de piquenique","local de piquenique"],
      zh: ["野餐区","公园野餐","野餐地点"],
      ja: ["ピクニックエリア","公園ピクニック","ピクニックスポット"],
    },
    bbq: {
      en: ["bbq area","grill zone","picnic with bbq"],
      es: ["zona de barbacoa","parrilla","área de picnic con bbq"],
      fr: ["aire de barbecue","barbecue","aire de pique-nique avec bbq"],
      de: ["Grillplatz","BBQ Bereich","Picknick mit Grill"],
      it: ["area barbecue","zona grill","picnic con barbecue"],
      pt: ["zona de churrasco","parrilla","área de piquenique com churrasco"],
      zh: ["烧烤区","烤架区","烧烤野餐区"],
      ja: ["バーベキューエリア","グリルゾーン","BBQピクニック"],
    },
  
    /* ------------------------------ INDOOR / CULTURAL VENUES ----------------------------- */
    museum: {
      en: ["museum","art museum","history museum","exhibition"],
      es: ["museo","museo de arte","museo histórico","exposición"],
      fr: ["musée","musée d’art","musée historique","exposition"],
      de: ["Museum","Kunstmuseum","Historisches Museum","Ausstellung"],
      it: ["museo","museo d’arte","museo storico","mostra"],
      pt: ["museu","museu de arte","museu histórico","exposição"],
      zh: ["博物馆","艺术博物馆","历史博物馆","展览"],
      ja: ["博物館","美術館","歴史博物館","展示会"],
    },
    gallery: {
      en: ["art gallery","exhibition space","modern art gallery"],
      es: ["galería de arte","sala de exposiciones","galería de arte moderno"],
      fr: ["galerie d’art","espace d’exposition","galerie d’art moderne"],
      de: ["Kunstgalerie","Ausstellungsraum","Moderne Galerie"],
      it: ["galleria d’arte","spazio espositivo","galleria di arte moderna"],
      pt: ["galeria de arte","espaço de exposições","galeria de arte moderna"],
      zh: ["艺术画廊","展览空间","现代艺术画廊"],
      ja: ["アートギャラリー","展示スペース","現代美術ギャラリー"],
    },
    cinema: {
      en: ["cinema","movie theatre","film screening","independent cinema"],
      es: ["cine","sala de cine","proyección de película","cine independiente"],
      fr: ["cinéma","salle de cinéma","projection de film","cinéma indépendant"],
      de: ["Kino","Lichtspielhaus","Filmvorführung","Independent Kino"],
      it: ["cinema","sala cinematografica","proiezione di film","cinema indipendente"],
      pt: ["cinema","sala de cinema","exibição de filmes","cinema independente"],
      zh: ["电影院","电影放映","独立影院"],
      ja: ["映画館","シネマ","映画上映","インディペンデントシネマ"],
    },
    shopping: {
      en: ["local market","farmers market","shopping mall","food hall"],
      es: ["mercado local","mercado de agricultores","centro comercial","mercado gastronómico"],
      fr: ["marché local","marché fermier","centre commercial","halle alimentaire"],
      de: ["lokaler Markt","Wochenmarkt","Einkaufszentrum","Food Hall"],
      it: ["mercato locale","mercato contadino","centro commerciale","mercato alimentare"],
      pt: ["mercado local","mercado de agricultores","centro comercial","mercado gastronómico"],
      zh: ["本地市场","农贸市场","购物中心","美食广场"],
      ja: ["ローカルマーケット","ファーマーズマーケット","ショッピングモール","フードホール"],
    },
    cafe: {
      en: ["cafe","coffee shop","brunch place"],
      es: ["cafetería","café","lugar de brunch"],
      fr: ["café","salon de café","brunch"],
      de: ["Café","Kaffeeladen","Brunch Lokal"],
      it: ["caffetteria","bar caffè","brunch"],
      pt: ["cafeteria","café","brunch"],
      zh: ["咖啡馆","咖啡店","早午餐店"],
      ja: ["カフェ","コーヒーショップ","ブランチスポット"],
    },
    going_to_pub: {
      en: ["pub","bar","brewery","beer garden"],
      es: ["pub","bar","cervecería","terraza"],
      fr: ["pub","bar","brasserie","terrasse"],
      de: ["Pub","Bar","Brauerei","Biergarten"],
      it: ["pub","bar","birreria","giardino della birra"],
      pt: ["pub","bar","cervejaria","esplanada"],
      zh: ["酒吧","啤酒馆","酿酒厂","啤酒花园"],
      ja: ["パブ","バー","ブルワリー","ビアガーデン"],
    },
  
    /* ------------------------------ INDOOR SPORTS / STUDIOS ------------------------------ */
    indoor_swimming: {
      en: ["swimming pool","indoor pool","public pool"],
      es: ["piscina","piscina cubierta","piscina pública"],
      fr: ["piscine","piscine couverte","piscine publique"],
      de: ["Schwimmbad","Hallenbad","öffentliches Schwimmbad"],
      it: ["piscina","piscina coperta","piscina pubblica"],
      pt: ["piscina","piscina coberta","piscina pública"],
      zh: ["游泳馆","室内泳池","公共泳池"],
      ja: ["プール","屋内プール","公共プール"],
    },
    tennis: {
      en: ["tennis court","tennis club","indoor tennis"],
      es: ["pista de tenis","club de tenis","tenis indoor"],
      fr: ["terrain de tennis","club de tennis","tennis indoor"],
      de: ["Tennisplatz","Tennisverein","Indoor Tennis"],
      it: ["campo da tennis","circolo tennis","tennis indoor"],
      pt: ["quadra de ténis","clube de ténis","ténis indoor"],
      zh: ["网球场","网球俱乐部","室内网球"],
      ja: ["テニスコート","テニスクラブ","インドアテニス"],
    },
    padel: {
      en: ["padel court","padel club"],
      es: ["pista de pádel","club de pádel"],
      fr: ["terrain de padel","club de padel"],
      de: ["Padelplatz","Padelclub"],
      it: ["campo da padel","club di padel"],
      pt: ["quadra de padel","clube de padel"],
      zh: ["帕德尔球场","帕德尔俱乐部"],
      ja: ["パデルコート","パデルクラブ"],
    },
    squash: {
      en: ["squash court","squash club"],
      es: ["pista de squash","club de squash"],
      fr: ["court de squash","club de squash"],
      de: ["Squashcourt","Squashclub"],
      it: ["campo da squash","club di squash"],
      pt: ["quadra de squash","clube de squash"],
      zh: ["壁球场","壁球俱乐部"],
      ja: ["スカッシュコート","スカッシュクラブ"],
    },
    badminton: {
      en: ["badminton court","badminton hall","sports hall"],
      es: ["pista de bádminton","pabellón de bádminton","polideportivo"],
      fr: ["terrain de badminton","salle de badminton","gymnase"],
      de: ["Badmintonfeld","Badmintonhalle","Sporthalle"],
      it: ["campo da badminton","palestra badminton","palazzetto"],
      pt: ["quadra de badminton","ginásio de badminton","pavilhão"],
      zh: ["羽毛球场","羽毛球馆","体育馆"],
      ja: ["バドミントンコート","バドミントンホール","スポーツホール"],
    },
    table_tennis: {
      en: ["table tennis","ping pong club","sports hall"],
      es: ["tenis de mesa","club de ping pong","polideportivo"],
      fr: ["tennis de table","club de ping-pong","salle de sport"],
      de: ["Tischtennis","Ping-Pong Club","Sporthalle"],
      it: ["tennis tavolo","club ping pong","palazzetto"],
      pt: ["ténis de mesa","clube de pingue-pongue","ginásio"],
      zh: ["乒乓球","乒乓球俱乐部","体育馆"],
      ja: ["卓球","ピンポンクラブ","スポーツホール"],
    },
    pickleball: {
      en: ["pickleball court","indoor pickleball"],
      es: ["pista de pickleball","pickleball indoor"],
      fr: ["terrain de pickleball","pickleball indoor"],
      de: ["Pickleballplatz","Indoor Pickleball"],
      it: ["campo da pickleball","pickleball indoor"],
      pt: ["quadra de pickleball","pickleball indoor"],
      zh: ["匹克球场","室内匹克球"],
      ja: ["ピックルボールコート","インドア・ピックルボール"],
    },
    volleyball_indoor: {
      en: ["volleyball court","indoor volleyball","sports hall"],
      es: ["pista de voleibol","voleibol indoor","pabellón"],
      fr: ["terrain de volley","volley en salle","gymnase"],
      de: ["Volleyballfeld","Hallenvolleyball","Sporthalle"],
      it: ["campo da pallavolo","volley indoor","palazzetto"],
      pt: ["quadra de voleibol","voleibol indoor","pavilhão"],
      zh: ["排球场","室内排球","体育馆"],
      ja: ["バレーボールコート","インドアバレー","スポーツホール"],
    },
    climbing_gym: {
      en: ["climbing gym","bouldering gym","indoor climbing"],
      es: ["rocódromo","boulder","escalada interior"],
      fr: ["salle d’escalade","bloc","escalade en salle"],
      de: ["Kletterhalle","Boulderhalle","Indoor Klettern"],
      it: ["palestra di arrampicata","boulder","arrampicata indoor"],
      pt: ["ginásio de escalada","boulder","escalada indoor"],
      zh: ["攀岩馆","抱石馆","室内攀岩"],
      ja: ["クライミングジム","ボルダリングジム","インドアクライミング"],
    },
    gym_workout: {
      en: ["gym","fitness centre","weight training","workout studio"],
      es: ["gimnasio","centro de fitness","pesas","sala de entrenamiento"],
      fr: ["salle de sport","centre fitness","musculation","studio d’entraînement"],
      de: ["Fitnessstudio","Trainingszentrum","Gewichtstraining"],
      it: ["palestra","centro fitness","sala pesi","studio di allenamento"],
      pt: ["ginásio","centro fitness","musculação","estúdio de treino"],
      zh: ["健身房","健身中心","力量训练","训练工作室"],
      ja: ["ジム","フィットネスセンター","筋トレ","ワークアウトスタジオ"],
    },
    yoga: {
      en: ["yoga studio","yoga class","wellness centre"],
      es: ["estudio de yoga","clase de yoga","centro de bienestar"],
      fr: ["studio de yoga","cours de yoga","centre de bien-être"],
      de: ["Yogastudio","Yogakurs","Wellnesszentrum"],
      it: ["studio di yoga","lezione di yoga","centro benessere"],
      pt: ["estúdio de yoga","aula de yoga","centro de bem-estar"],
      zh: ["瑜伽馆","瑜伽课","健康中心"],
      ja: ["ヨガスタジオ","ヨガクラス","ウェルネスセンター"],
    },
    pilates: {
      en: ["pilates studio","reformer pilates","pilates class"],
      es: ["estudio de pilates","pilates reformer","clase de pilates"],
      fr: ["studio de pilates","pilates reformer","cours de pilates"],
      de: ["Pilatesstudio","Reformer Pilates","Pilateskurs"],
      it: ["studio di pilates","reformer pilates","lezione di pilates"],
      pt: ["estúdio de pilates","pilates reformer","aula de pilates"],
      zh: ["普拉提工作室","普拉提床","普拉提课程"],
      ja: ["ピラティススタジオ","リフォーマーピラティス","ピラティスクラス"],
    },
    martial_arts: {
      en: ["martial arts dojo","karate club","judo club"],
      es: ["dojo de artes marciales","club de kárate","club de judo"],
      fr: ["dojo d’arts martiaux","club de karaté","club de judo"],
      de: ["Kampfsportdojo","Karateclub","Judoclub"],
      it: ["dojo arti marziali","club di karate","club di judo"],
      pt: ["dojo de artes marciais","clube de karaté","clube de judo"],
      zh: ["武术馆","空手道俱乐部","柔道俱乐部"],
      ja: ["武道道場","空手クラブ","柔道クラブ"],
    },
    dance: {
        en: ["nightclub","dance class","ballet school"],
        es: ["club nocturno","discoteca","escuela de ballet"],
        fr: ["boîte de nuit","cours de danse","école de ballet"],
        de: ["Nachtclub","Tanzkurs","Ballettschule"],
        it: ["discoteca","lezione di danza","scuola di balletto"],
        pt: ["boate","aula de dança","escola de balé"],
        zh: ["夜店","舞蹈课","芭蕾学校"],
        ja: ["ナイトクラブ","ダンス教室","バレエ学校"],
      }
  };